### ISSUE TITLE
[bug]import Err

### ISSUE THREAD

**Issue by STOI123** [ActivityWatch/activitywatch#1050]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Win11.  and  Android
- **ActivityWatch version**: AW Version:  v0.12.2 . Android v0.12.1

## Describe the bug

Import from android to PC
have del android data before and import it again, don't know has anything to do with that

## To Reproduce
export from Android to Windows

## Additional context

2024-04-27 23:01:33 [ERROR]: Exception on /api/0/import [POST]  (aw-server:1449)
Traceback (most recent call last):
  File "peewee.py", line 3237, in execute_sql
sqlite3.IntegrityError: NOT NULL constraint failed: bucketmodel.datastr

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask\app.py", line 1517, in full_dispatch_request
  File "flask\app.py", line 1503, in dispatch_request
  File "aw_server\rest.py", line 46, in decorator
  File "flask_restx\api.py", line 405, in wrapper
  File "flask\views.py", line 84, in view
  File "flask_restx\resource.py", line 46, in dispatch_request
  File "aw_server\rest.py", line 377, in post
  File "aw_server\api.py", line 131, in import_all
  File "aw_server\api.py", line 106, in import_bucket
  File "aw_datastore\datastore.py", line 56, in create_bucket
  File "aw_datastore\storages\peewee.py", line 152, in create_bucket
  File "peewee.py", line 6532, in create
  File "peewee.py", line 6742, in save
  File "peewee.py", line 1962, in inner
  File "peewee.py", line 2033, in execute
  File "peewee.py", line 2838, in _execute
  File "peewee.py", line 2551, in _execute
  File "peewee.py", line 3250, in execute
  File "peewee.py", line 3244, in execute_sql
  File "peewee.py", line 3010, in __exit__
  File "peewee.py", line 192, in reraise
  File "peewee.py", line 3237, in execute_sql
peewee.IntegrityError: NOT NULL constraint failed: bucketmodel.datastr
2024-04-27 23:01:33 [INFO ]: 500 (127.0.0.1): [35m[1mPOST /api/0/import HTTP/1.1[0m  (flask:25)

**Comment by STOI123** [comment]
Furthermore, the log output on the wrong file, It should be on 4-27, yet I found them on 4-23
