### ISSUE TITLE
AW-Watcher-Window randomly not tracking

### ISSUE THREAD

**Issue by shoaib281** [ActivityWatch/activitywatch#1060]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Ubuntu
- **ActivityWatch version**: v0.12.2

## Describe the bug
Aw-watcher-window randomly doesn't track anything. 

Unclear how to reproduce. To resolve, restart activity watch.

## Documentation
![image](https://github.com/ActivityWatch/activitywatch/assets/63969100/3c1b8c9d-a949-435a-84fc-9afd3db9a181)
![image](https://github.com/ActivityWatch/activitywatch/assets/63969100/5b39df40-d839-472a-825d-6e6da9fa3fb1)

**aw-watcher-window log**
2024-05-13 20:36:30 [ERROR]: Exception thrown while trying to get active window  (aw_watcher_window.main:124)
Traceback (most recent call last):
  File "aw_watcher_window/main.py", line 106, in heartbeat_loop
  File "aw_watcher_window/lib.py", line 59, in get_current_window
  File "aw_watcher_window/lib.py", line 17, in get_current_window_linux
  File "aw_watcher_window/xlib.py", line 67, in get_window_name
  File "Xlib/xobject/drawable.py", line 476, in get_full_property
  File "Xlib/xobject/drawable.py", line 455, in get_property
  File "Xlib/protocol/rq.py", line 1368, in __init__
  File "Xlib/protocol/rq.py", line 1380, in reply
  File "Xlib/protocol/display.py", line 612, in send_and_recv
  File "Xlib/protocol/display.py", line 719, in parse_response
  File "Xlib/protocol/display.py", line 745, in parse_error_response
AttributeError: 'BadRRModeError' object has no attribute 'sequence_number'

**Comment by jp-man25** [comment]
Having the same problem on Windows 10. Started happening recently. I restarted it and it stopped working again the next day.

**Comment by yuis-ice** [comment]
Same on Windows 10. But for me, it's not "randomly", but it "stops" (randomly).

**Comment by ErikBjare** [comment]
The Linux-specific issue here was fixed (see https://github.com/ActivityWatch/aw-watcher-window/issues/89), as well as the macOS issue (https://github.com/ActivityWatch/activitywatch/issues/1052) which is unrelated but with similar outcome.

If this happens on Windows, please open an issue for that specifically.
