### ISSUE TITLE
After 0.12.1 -> 0.13.1 update "Activity" page doesn't show AFK/Window/Browser events

### ISSUE THREAD

**Issue by AlexanderMakarov** [ActivityWatch/activitywatch#1076]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **Linux Mint 21.3 Virginia base: Ubuntu 22.04 jammy Desktop: Xfce 4.18.1 tk: Gtk 3.24.33**: 
- **v0.13.1**: 

## Describe the bug
After updating from v0.12.1 to v0.13.1 on http://localhost:5600/#/activity/host_name/view/ nothing is displayed in "Summary", "Window", "Browser" tabs. Only "Editor" tab shows data.

While on http://localhost:5600/#/timeline I see all events, there are window and AFK events in http://localhost:5600/#/buckets. Other pages also work. From errors in log I see only `Gtk-Message: 09:31:31.782: Failed to load module "xapp-gtk3-module"` which doesn't look relevant.

Default configuration in "/home/user/.config/activitywatch" (everything is commented out). Default Views configuration on http://localhost:5600/#/activity/host_name/view/ 

## To Reproduce
1. Use 0.12.1 version some time. Installed from sources.
2. Download https://github.com/ActivityWatch/activitywatch/releases/download/v0.13.1/activitywatch-v0.13.1-linux-x86_64.zip
3. Remove "/home/user/activitywatch/" and unpack ZIP into it.
4. Run `/home/user/activitywatch/./aw-qt` and go to http://localhost:5600/#/activity/host_name/view/

## Expected behavior
![image](https://github.com/ActivityWatch/activitywatch/assets/2630978/d9197ed2-831e-4ab7-a2de-86e897cbf3d5)
(from old v0.12.1 which I have to revert back)

## Actual behavior
![image](https://github.com/ActivityWatch/activitywatch/assets/2630978/06e8075a-45c7-4265-8d98-e25bc3aa33e0)

**Comment by qcol** [comment]
It's the same with me. At first it didn't show any data, I changed to server-rust (I used that before), after restart it shows the old data but doesn't register new data. Ubuntu 22.04 (xubuntu).

**Comment by BelKed** [comment]
@AlexanderMakarov, you might want to try installing `xapp-gtk3-module` as the error suggests :)
https://askubuntu.com/questions/1396739/failed-to-load-module-xapp-gtk3-module

**Comment by qcol** [comment]
In my case the xapp is installed, so this is probably not the cause (I don't see such an error in the logs).

**Comment by qcol** [comment]
> It's the same with me. At first it didn't show any data, I changed to server-rust (I used that before), after restart it shows the old data but doesn't register new data. Ubuntu 22.04 (xubuntu).

edit: sorry, events are recorded! (I see it in Timeline, However, I do not see them in the main chart view. Exactly the same as Alexander) 

```
2024-06-21 09:04:11 [INFO ]: aw-watcher-window started  (aw_watcher_window.main:62)
2024-06-21 09:04:12 [INFO ]: window-watcher stopped because parent process died  (aw_watcher_window.main:101)
2024-06-21 09:04:12 [INFO ]: Connection to aw-server established by aw-watcher-window  (aw_client.client:447)

```
Interestingly, in the log I have that the process has been killed. This makes it all the more strange, as events do register though. 

It is possible that the problem is related to the XFCE Environment (as well as the icon in the tray, which I also cannot get for several versions)

**Comment by qcol** [comment]
I have found the solution! I had forgotten that I was using the scripts for Gnome in the previous version:
https://docs.activitywatch.net/en/latest/running-on-gnome.html#running-on-gnome

These scripts also apply to **XFCE**-based environments (e.g. **Xubuntu**)

The problem is probably related to the **tray icon** which I could never get in the last versions either. Therefore activitywatch also works run with the --no-gui option, as described here:
https://github.com/ActivityWatch/activitywatch/issues/960#issuecomment-1867638079

**Comment by AlexanderMakarov** [comment]
> Therefore activitywatch also works run with the --no-gui option, as described here:
> [#960 (comment)](https://github.com/ActivityWatch/activitywatch/issues/960#issuecomment-1867638079)

Unfortunately it is not related issue.

Because I don't see logs
```
window-watcher stopped
afkwatcher stopped
```
They are actually working - I may see events in "Timeline". But I can't see events on "Activity" page (except "Editor" ones). Issue is just in this page, not in the events gathering/filtering system.

**Comment by Humam-Hamdan** [comment]
had the same issue, tried it without waylad... it worked. (ubuntu 24.04 LTS)

**Comment by Pineapplenuts** [comment]
I have similar issue where it doesn't detect browser usage and considers in browser streaming content as away from keyboard resulting in everything being inaccurate

**Comment by vitaut7** [comment]
Hi, i have the same problem
aw_watcher_window.log:

`2024-07-15 21:30:17 [ERROR]: Exception thrown while trying to get active window  (aw_watcher_window.main:124)
Traceback (most recent call last):
  File "aw_watcher_window\main.py", line 106, in heartbeat_loop
  File "aw_watcher_window\lib.py", line 70, in get_current_window
  File "aw_watcher_window\lib.py", line 39, in get_current_window_windows
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "aw_watcher_window\windows.py", line 5, in <module>
ImportError: DLL load failed while importing win32api: The specified procedure could not be found.`

**Comment by Programmer484** [comment]
Same issue here as the original poster. Fresh install.

The timeline works, summary appears frozen. 

Tried restarting ActivityWatch, summary hasn't changed. 

Operating System is Ubuntu 22.04.5 LTS

EDIT:
Turns out the time was all being registered as AFK time even though was I definitely using Google Chrome.

EDIT: 
Version 12.3 has the same issue. Not a version issue. Could be Wayland like 0xbrayo mentioned below

<img width="1397" height="745" alt="Image" src="https://github.com/user-attachments/assets/a897e723-260d-4f5c-ade7-7f4d6f32594c" />

<img width="1480" height="604" alt="Image" src="https://github.com/user-attachments/assets/a35e141e-3e83-414f-9948-daf5ef6101dc" />

**Comment by 0xbrayo** [comment]
The default window watcher works poorly with wayland, install [awatcher](https://github.com/2e3s/awatcher). Follow the setup instructions in the readme. No idea why it breaks after the update though.

**Comment by RyanLin-InfEvo** [comment]
For ubuntu 24.04.3, it only works on x11. It don't work correctly with Wayland

**Comment by 0xbrayo** [comment]
> For ubuntu 24.04.3, it only works on x11. It don't work correctly with Wayland

Awatcher doesn't work with wayland? Have you installed the additional gnome extensions. You can find the links in awatcher's README

**Comment by TimeToBuildBob** [comment]
## Triage Summary

This thread conflates several distinct issues. Here's a breakdown to help folks find the right fix:

### Issue A: Activity page empty but Timeline works (Wayland users)
**Affects**: Ubuntu 22.04+, Fedora, other Wayland-default distros
**Root cause**: `aw-watcher-window` uses X11 APIs that don't work on Wayland, so no window events are captured. The Activity view relies on window events combined with AFK events, so it shows nothing.
**Fix**: Install [awatcher](https://github.com/2e3s/awatcher) which has native Wayland support. On GNOME, you'll also need the extensions listed in awatcher's README. Tracked in ActivityWatch/activitywatch#92.

### Issue B: Activity page empty on XFCE/Xubuntu
**Affects**: XFCE-based desktops
**Root cause**: Missing GNOME-compatible scripts needed for window detection. As @qcol found, the [GNOME running guide](https://docs.activitywatch.net/en/latest/running-on-gnome.html#running-on-gnome) also applies to XFCE.
**Fix**: Follow the GNOME setup instructions linked above.

### Issue C: `ImportError: DLL load failed` on Windows
**Affects**: Windows, reported by @vitaut7
**Root cause**: Bundled `win32api` DLL incompatibility in the PyInstaller build.
**Fix**: This is a separate issue — tracked in ActivityWatch/aw-watcher-window#90.

### Issue D: Browser streaming = AFK
**Affects**: All platforms, reported by @Pineapplenuts
**Root cause**: `aw-watcher-afk` only checks keyboard/mouse input. Passive video watching = AFK.
**Fix**: Use a media player watcher like [aw-watcher-media-player](https://github.com/2e3s/aw-watcher-media-player), or configure the "always count as active" feature per-app. Tracked in ActivityWatch/activitywatch#261.

### Diagnostic steps for anyone still hitting this:
```bash
# 1. Check if window events exist at all
curl -s http://localhost:5600/api/0/buckets | python3 -m json.tool | grep '"id"'
# Look for "aw-watcher-window" bucket

# 2. Check if events are being recorded today
curl -s "http://localhost:5600/api/0/buckets/aw-watcher-window_$(hostname)/events?limit=5" | python3 -m json.tool
# If empty: window watcher isn't working (likely Wayland issue A)

# 3. Check session type
echo $XDG_SESSION_TYPE
# "wayland" → use awatcher; "x11" → check logs for errors
```

This issue could likely be closed in favor of the more specific trackers (ActivityWatch/activitywatch#92 for Wayland, ActivityWatch/aw-watcher-window#90 for Windows). The Activity page itself works fine — the underlying problem is always about missing events from watchers.
