### ISSUE TITLE
Does not run on Fedora 40 Workstation

### ISSUE THREAD

**Issue by datalot-369** [ActivityWatch/activitywatch#1077]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [ ] I have searched the issues of this repo and believe that this is not a duplicate.
 **Note: Actually, I don't think that an average user should search for terminal outputs on the Internet in order to run a time tracking app. It's already too much filling up a whole bug report. Most just delete it and next app.**

- **OS name and version**: Fedora 40 Workstation
- **ActivityWatch version**: v0.13.1 AppImage

## Describe the bug
Does not run.

## To Reproduce
1. Download the AppImage
2. Right Click > Properties > Executable as program [ON]
3. Double Click or ./appimagelocation

## Expected behavior
I mean...

## Documentation

[aw-qt_2024-06-21T23-44-31.log](https://github.com/user-attachments/files/15934977/aw-qt_2024-06-21T23-44-31.log)

## Additional context
```
datalot@fedora:~/Downloads/binary-portable$ ./activitywatch-linux-x86_64.AppImage 
2024-06-21 23:44:54 [INFO ]: Started aw-qt...  (aw_qt.main:53)
2024-06-21 23:44:54 [WARNING]: Found matching file but was not executable: /tmp/.mount_activiRQc71F/aw-qt.desktop  (aw_qt.manager:64)
2024-06-21 23:44:54 [INFO ]: Found 8 bundled modules  (aw_qt.manager:85)
2024-06-21 23:44:54 [INFO ]: Found 0 system modules  (aw_qt.manager:119)
2024-06-21 23:44:54 [INFO ]: Starting module aw-server  (aw_qt.manager:148)
2024-06-21 23:44:54 [INFO ]: Starting module aw-watcher-afk  (aw_qt.manager:148)
2024-06-21 23:44:54 [INFO ]: Starting module aw-watcher-window  (aw_qt.manager:148)
2024-06-21 23:44:54 [INFO ]: Creating trayicon...  (aw_qt.trayicon:208)
/tmp/.mount_activiRQc71F/aw-qt: symbol lookup error: /tmp/.mount_activiRQc71F/libQt6WaylandClient.so.6: undefined symbol: wl_proxy_marshal_flags
Traceback (most recent call last):
  File "PyInstaller/hooks/rthooks/pyi_rth_inspect.py", line 47, in <module>
Traceback (most recent call last):
  File "PyInstaller/hooks/rthooks/pyi_rth_inspect.py", line 47, in <module>
  File "PyInstaller/hooks/rthooks/pyi_rth_inspect.py", line 14, in _pyi_rthook
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "PyInstaller/hooks/rthooks/pyi_rth_inspect.py", line 14, in _pyi_rthook
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "inspect.py", line 39, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "inspect.py", line 41, in <module>
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "importlib/__init__.py", line 58, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen zipimport>", line 259, in load_module
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "linecache.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen zipimport>", line 241, in load_module
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen zipimport>", line 709, in _get_module_code
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "<frozen zipimport>", line 536, in _get_data
  File "tokenize.py", line 32, in <module>
ConnectionAbortedError: [Errno 103] Software caused connection abort: '/tmp/.mount_activiRQc71F/aw-watcher-afk/base_library.zip'
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
[1927237] Failed to execute script 'pyi_rth_inspect' due to unhandled exception!
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "re.py", line 125, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1397, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1378, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 423, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 716, in spec_from_file_location
  File "<frozen zipimport>", line 191, in get_filename
  File "<frozen zipimport>", line 709, in _get_module_code
  File "<frozen zipimport>", line 536, in _get_data
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/.mount_activiRQc71F/aw-server/base_library.zip'
[1927236] Failed to execute script 'pyi_rth_inspect' due to unhandled exception!
Traceback (most recent call last):
  File "PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py", line 107, in <module>
  File "PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py", line 18, in _pyi_rthook
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "multiprocessing/__init__.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "multiprocessing/context.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "multiprocessing/reduction.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1397, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1378, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 423, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 716, in spec_from_file_location
  File "<frozen zipimport>", line 191, in get_filename
  File "<frozen zipimport>", line 709, in _get_module_code
  File "<frozen zipimport>", line 536, in _get_data
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/.mount_activiRQc71F/aw-watcher-window/base_library.zip'
[1927238] Failed to execute script 'pyi_rth_multiprocessing' due to unhandled exception!
```

**Comment by Ph15** [comment]
Same over here: I have tried to install the AW AppImage, but my session crashed with a black screen and a weird code line when I first tried to open it. Running on Fedora 40 with Gnome × Wayland.

Is there any way to get the app working through the .zip install or Git clone?
If so, how to proceed? (I'm quite new to Linux, and have not been able to figure out how to install an app from a .zip file...)

**Comment by Ph15** [comment]
P.S.: I have also tried installing the app through the .zip file and launching aw-qt, but I get no GUI. I can see in my monitor that aw-server and aw-watcher-window are running, but that's about it.

**Comment by ErikBjare** [comment]
Given `symbol lookup error: /tmp/.mount_activiRQc71F/libQt6WaylandClient.so.6: undefined symbol: wl_proxy_marshal_flags`, this issue seems similar to https://github.com/rbreu/beeref/issues/102

Upstream bug in Qt: https://bugreports.qt.io/browse/QTBUG-114635

Which suggests that, to fix this in a future release, we can update Wayland in CI:

> [owillebo](https://bugreports.qt.io/secure/ViewProfile.jspa?name=owillebo) 's analysis is correct: if wl_proxy_marshal_flags was introduced in wayland version 1.19.91 then you need at least wayland >= 1.19.91 when building both Qt and Pyside.

@nonno-cicala Then that's probably due to incompatibilities with system Wayland libraries.

Removing the included Qt-related library files, instead relying on system versions which are compatible with Wayland libs, is a legitimate workaround. But the `QTA_QPA_PLATFORM=xcb` might be better and would work for the AppImage too.

@Ph15 If you run it from the terminal, what is the output? Similar as the above? The QTA_QPA_PLATFORM trick might work for you too.

**Comment by Ph15** [comment]
Hello @ErikBjare!
Thanks for taking the time to answer.
I am not techy enough at the moment to know how to use the `QTA_QPA_PLATFORM=xcb` trick.
Are there any simple steps I can follow to do so?

**Comment by Humam-Hamdan** [comment]
ig you can just install Xorg and call it a day.

**Comment by wojnilowicz** [comment]
On Fedora you could at least try https://copr.fedorainfracloud.org/coprs/wojnilowicz/activitywatch/
It works for me on Fedora 41.

**Comment by guillermodotn** [comment]
Thanks, @wojnilowicz! Your COPR package repo works great.

I’ve created a little [guide](https://gist.github.com/guillermodotn/ec9ac40932b210d6216d17cc2d61c631) to run it as a user-level service.

Have a look, @Ph15 maybe this setup will convince you.

**Comment by Oneechan69** [comment]
@wojnilowicz The copr no longer exists?

**Comment by wojnilowicz** [comment]
> [@wojnilowicz](https://github.com/wojnilowicz) The copr no longer exists?

I deleted it. All the packages are now in the official repository as seen at:
1. https://src.fedoraproject.org/rpms/aw-server-rust
2. https://src.fedoraproject.org/rpms/awatcher
3. https://src.fedoraproject.org/rpms/python-aw-qt

Do you need it for something?

**Comment by wojnilowicz** [comment]
> Thanks, [@wojnilowicz](https://github.com/wojnilowicz)! Your COPR package repo works great.
> 
> I’ve created a little [guide](https://gist.github.com/guillermodotn/ec9ac40932b210d6216d17cc2d61c631) to run it as a user-level service.
> 
> Have a look, [@Ph15](https://github.com/Ph15) maybe this setup will convince you.

Recently an user asked about GNOME support at https://discussion.fedoraproject.org/t/wojnilowicz-activitywatch/115922/5 I hope he'll get your guide. Thanks.

**Comment by Oneechan69** [comment]
Will there eventually be just one package to install with dnf or will the documentation be update to install all three?

**Comment by Oneechan69** [comment]
`sudo dnf install awatcher` doesn't work for me right now.

**Comment by 0xbrayo** [comment]
> `sudo dnf install awatcher` doesn't work for me right now.

Install the rpm from releases https://github.com/2e3s/awatcher

**Comment by wojnilowicz** [comment]
> Will there eventually be just one package to install with dnf or will the documentation be update to install all three?

No.

> `sudo dnf install awatcher` doesn't work for me right now.

Did you try `sudo dnf install aw-awatcher`?

**Comment by Oneechan69** [comment]
```
sudo dnf install aw-watcher -y
Updating and loading repositories:
Repositories loaded.
Failed to resolve the transaction:
No match for argument: aw-watcher
You can try to add to command line:
  --skip-unavailable to skip unavailable packages
```

**Comment by 0xbrayo** [comment]
@Oneechan69  It's `aw-awatcher` not `aw-watcher`

**Comment by Oneechan69** [comment]
Can’t wait for documentation to get updated lol

**Comment by 0xbrayo** [comment]
> Can’t wait for documentation to get updated lol

Did `sudo dnf install aw-awatcher` work?

**Comment by Oneechan69** [comment]
Yes

**Comment by xplosionmind** [comment]
I am reproducing this issue on Fedora 42, GNOME 48, kernel 6.14.4-300.fc42.x86_64

log:

```
./activitywatch.appimage
2025-05-02 12:10:21 [INFO ]: Started aw-qt...  (aw_qt.main:53)
2025-05-02 12:10:21 [WARNING]: Found matching file but was not executable: /tmp/.mount_activisuoTu2/aw-qt.desktop  (aw_qt.manager:64)
2025-05-02 12:10:21 [INFO ]: Found 8 bundled modules  (aw_qt.manager:85)
2025-05-02 12:10:21 [INFO ]: Found 0 system modules  (aw_qt.manager:119)
2025-05-02 12:10:21 [INFO ]: Starting module aw-server  (aw_qt.manager:148)
2025-05-02 12:10:21 [INFO ]: Starting module aw-watcher-afk  (aw_qt.manager:148)
2025-05-02 12:10:21 [INFO ]: Starting module aw-watcher-window  (aw_qt.manager:148)
2025-05-02 12:10:21 [INFO ]: Creating trayicon...  (aw_qt.trayicon:208)
/tmp/.mount_activisuoTu2/aw-qt: symbol lookup error: /tmp/.mount_activisuoTu2/libQt6WaylandClient.so.6: undefined symbol: wl_proxy_marshal_flags
Traceback (most recent call last):
  File "PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py", line 117, in <module>
Traceback (most recent call last):
  File "PyInstaller/loader/pyimod02_importers.py", line 187, in get_code
  File "PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py", line 27, in _pyi_rthook
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "PyInstaller/loader/pyimod01_archive.py", line 134, in extract
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
ConnectionAbortedError: [Errno 103] Software caused connection abort: '/tmp/.mount_activisuoTu2/aw-watcher-afk/aw-watcher-afk'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/hooks/rthooks/pyi_rth_pkgres.py", line 158, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "PyInstaller/hooks/rthooks/pyi_rth_pkgres.py", line 33, in _pyi_rthook
  File "pathlib.py", line 4, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "pathlib.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 400, in exec_module
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "PyInstaller/loader/pyimod02_importers.py", line 189, in get_code
  File "<frozen zipimport>", line 259, in load_module
ImportError: PyiFrozenImporter cannot handle module 'fnmatch'
[31863] Failed to execute script 'pyi_rth_pkgres' due to unhandled exception!
  File "ntpath.py", line 259, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1526, in find_spec
Traceback (most recent call last):
  File "PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py", line 107, in <module>
  File "<frozen importlib._bootstrap_external>", line 1569, in _fill_cache
  File "PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py", line 18, in _pyi_rthook
ConnectionAbortedError: [Errno 103] Software caused connection abort: '/tmp/.mount_activisuoTu2/aw-server'
[31862] Failed to execute script 'pyi_rth_pkgutil' due to unhandled exception!
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "multiprocessing/__init__.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "multiprocessing/context.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "multiprocessing/reduction.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "pickle.py", line 103, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1526, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1569, in _fill_cache
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/.mount_activisuoTu2/aw-watcher-window'
[31864] Failed to execute script 'pyi_rth_multiprocessing' due to unhandled exception!
```

**Comment by beedell-roke** [comment]
@0xbrayo, who is "we"? The AW development team?

**Comment by 0xbrayo** [comment]
Yes the AW development team.
