### ISSUE TITLE
High CPU usage since upgrading to  v0.13.1 (rust)

### ISSUE THREAD

**Issue by s1lverkin** [ActivityWatch/activitywatch#1082]
- **OS name and version**: Windows 10 
- **ActivityWatch version**:  v0.13.1 (rust)

## Describe the bug

Until update my aw-server-rust.exe process was not eating so much CPU than the newest version does. Right now, getting constantly 3 to 10% cpu usage spikes every few seconds, especially when switching out tabs in Edge, or switching out applications, but it does even spike when I am not doing anything.

Previously the load on cpu was like 3 times smaller.

Does anyone observed similar behavior? Right now aw-server-rust.exe is my #1 app on task manager in terms of cpu usage (despite actively using web browser)...

**Comment by s1lverkin** [comment]
I am pretty sure it is due to aw-watcher-window, here's a snippet of it's log file:

`Traceback (most recent call last):
  File "aw_client\client.py", line 470, in _dispatch_request
  File "aw_client\client.py", line 50, in g
  File "aw_client\client.py", line 124, in _post
  File "requests\api.py", line 115, in post
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 519, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5600): Max retries exceeded with url: /api/0/buckets/aw-watcher-window_xxx/heartbeat?pulsetime=2.0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C0BE533D90>: Failed to establish a new connection: [WinError 10061] 
2024-07-01 11:40:38 [ERROR]: Unknown error, not retrying: {'id': None, 'timestamp': '2024-07-01T09:40:34.180000+00:00', 'duration': 0.0, 'data': {'app': 'notepad++.exe', 'title': 'C:\\Users\\xxx\\AppData\\Local\\activitywatch\\activitywatch\\Logs\\aw-watcher-window\\aw-watcher-window_2024-06-29T11-16-26.log - Notepad++'}}  (aw_client.client:501)
Traceback (most recent call last):
  File "urllib3\connection.py", line 174, in _new_conn
  File "urllib3\util\connection.py", line 95, in create_connection
  File "urllib3\util\connection.py", line 85, in create_connection
ConnectionRefusedError: [WinError 10061]`

**Comment by s1lverkin** [comment]
Nvm, after restart it didn't work, but when I launched it as a non admin user it started to work normally...

**Comment by s1lverkin** [comment]
Nvm, after restart it didn't work, but when I launched it as a non admin user it started to work normally...
