### ISSUE TITLE
Aw window Watcher fail to run on Windows

### ISSUE THREAD

**Issue by TheInspectator** [ActivityWatch/activitywatch#1095]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 11 Home, Version: 23H2
- **ActivityWatch version**: v0.13.1

## Describe the bug
Module aw-window-watcher won't run.

## To Reproduce
  Steps to reproduce the behavior, for example:
    1. Go to C:\Users\<user name>\AppData\Local\Programs\ActivityWatch\aw-watcher-window
    2. Click on aw-watcher-window.exe

## Expected behavior
I expected it to work.

## Documentation
The following constantly repeats:
2024-08-16 09:45:39 [INFO ]: Connection to aw-server established by aw-watcher-window  (aw_client.client:447)
2024-08-16 09:45:40 [ERROR]: Exception thrown while trying to get active window  (aw_watcher_window.main:124)
Traceback (most recent call last):
  File "aw_watcher_window\main.py", line 106, in heartbeat_loop
  File "aw_watcher_window\lib.py", line 70, in get_current_window
  File "aw_watcher_window\lib.py", line 39, in get_current_window_windows
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "aw_watcher_window\windows.py", line 5, in <module>
ImportError: DLL load failed while importing win32api: The specified procedure could not be found.
## Additional context
I've since installed python and pywin32 but no change. By the way I found data that it worked a year ago even though I didn't install this till yesterday.

**Comment by a-fakhri** [comment]
Same issue here

**Comment by Herdo** [comment]
Got the same issue :(

**Comment by heppson** [comment]
Same for me on 0.13.2

**Comment by redmondChris** [comment]
Very similar issue happening for me, also. (Ref. https://forum.activitywatch.net/t/no-results-for-aw-watcher-window/3476.) 

Similar to @TheInspectator , I'm seeing the following lines in the log, repeated over and over.

```
2025-02-13 11:44:16 [ERROR]: Exception thrown while trying to get active window  (aw_watcher_window.main:133)
Traceback (most recent call last):
  File "aw_watcher_window\main.py", line 115, in heartbeat_loop
  File "aw_watcher_window\lib.py", line 70, in get_current_window
  File "aw_watcher_window\lib.py", line 39, in get_current_window_windows
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "aw_watcher_window\windows.py", line 5, in <module>
ImportError: DLL load failed while importing win32api: The specified procedure could not be found.
```
Like @heppson , I'm running 0.13.2.

**Comment by MartenMM** [comment]
I've delved a bit deeper. This issue appears in 0.13.0 and onwards, rolling back to 0.12.2 fixes this for the time being. I also have 0.13.2 installed on a different machine and on that machine it seems to work _most of the time_ (I'm having different issues there that I need to get to the bottom of).

**Comment by redmondChris** [comment]
@MartenMM - I think I'd previously reinstalled 0.13.2 over itself when trying to work around this. Based on your comment, I just tried a clean install of 0.13.2, and it looks as if aw-watcher-window is functioning again. Thanks for the suggestion!
