### ISSUE TITLE
Always AFK - crash of aw-wather thread

### ISSUE THREAD

**Issue by letsruletheworld** [ActivityWatch/activitywatch#1122]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [ ] I have searched the issues of this repo and believe that this is not a duplicate.

installed 0.13.2 via AUR - Arch - but web interface reports 0.13.1

- **Manjaro testing**: 
- **ActivityWatch 0.13.1**: 

should be 0.13.2 though - see above

## Describe the bug

activity is not registered  - always shows AFK

## Additional context

seems to be python version 3.13.1 does not support  mouse listener. second computer with python 3.12.7 works fine. 

error log:

```
2024-12-26 15:58:58 [ERROR]: Unhandled exception in listener callback  (pynput.mouse.Listener:233)
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/pynput/_util/__init__.py", line 229, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python3.13/site-packages/pynput/_util/xorg.py", line 470, in _handler
    self._handle(self._display_stop, event)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '_thread._ThreadHandle' object is not callable
```

**Comment by Game4Move78** [comment]
You could follow the instructions [to build from source](https://docs.activitywatch.net/en/latest/installing-from-source.html). First replacing the line `pynput = "*"` in `aw-watcher-afk/pyproject.toml` with:
```
pynput = { git = "https://github.com/moses-palmer/pynput.git", branch = "fixup/listener-thread-handle" }`
```

Or switch to an older version of Python than 3.13.
