### ISSUE TITLE
Clean installation can't launch application

### ISSUE THREAD

**Issue by Titan-C** [ActivityWatch/activitywatch#155]
I wanted to give ActivityWatch a try.
I install from source from todays master. `make build` finishes without problem. Calling `aw-qt` fails
```
2017-12-12 22:37:02 [INFO ]: Starting module aw-server  (aw_qt.manager:46)
2017-12-12 22:37:02 [INFO ]: Starting module aw-watcher-window  (aw_qt.manager:46)
2017-12-12 22:37:02 [INFO ]: Starting module aw-watcher-afk  (aw_qt.manager:46)
2017-12-12 22:37:02 [INFO ]: Creating trayicon...  (aw_qt.trayicon:150)
/home/me/.virtualenvs/activitywatch/lib/python3.6/site-packages/aw_watcher_afk/afk.py:44: DeprecationWarning: Call to deprecated function setup_bucket, this warning will only show once per function.
  self.client.setup_bucket(self.bucketname, eventtype)
2017-12-12 22:37:03 [INFO ]: afkwatcher started  (aw_watcher_afk.afk:55)
2017-12-12 22:37:03 [INFO ]: Running watcher with poll time 1.0 seconds  (aw_watcher_window.main:35)
2017-12-12 22:37:03 [INFO ]: aw-watcher-window has started  (aw_watcher_window.main:44)
2017-12-12 22:37:03 [INFO ]: Using storage method: peewee  (aw_server.main:25)
2017-12-12 22:37:03 [INFO ]: Starting up...  (aw_server.main:30)
2017-12-12 22:37:03 [INFO ]: Using database file: /home/me/.local/share/activitywatch/aw-server/peewee-sqlite.v2.db  (aw_datastore.storages.peewee:111)
Traceback (most recent call last):
  File "/home/me/.virtualenvs/activitywatch/bin/aw-server", line 11, in <module>
    sys.exit(main())
  File "/home/me/.virtualenvs/activitywatch/lib/python3.6/site-packages/aw_server/main.py", line 32, in main
    testing=settings.testing, storage_method=storage_method)
  File "/home/me/.virtualenvs/activitywatch/lib/python3.6/site-packages/aw_server/server.py", line 58, in _start
    app.run(debug=testing, host=host, port=port, request_handler=FlaskLogHandler, use_reloader=False)
  File "/home/me/.virtualenvs/activitywatch/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/me/.virtualenvs/activitywatch/lib/python3.6/site-packages/werkzeug/serving.py", line 799, in run_simple
    inner()
  File "/home/me/.virtualenvs/activitywatch/lib/python3.6/site-packages/werkzeug/serving.py", line 759, in inner
    fd=fd)
  File "/home/me/.virtualenvs/activitywatch/lib/python3.6/site-packages/werkzeug/serving.py", line 651, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/home/me/.virtualenvs/activitywatch/lib/python3.6/site-packages/werkzeug/serving.py", line 562, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib64/python3.6/socketserver.py", line 453, in __init__
    self.server_bind()
  File "/usr/lib64/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib64/python3.6/socketserver.py", line 467, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 99] Cannot assign requested address
2017-12-12 22:37:04 [WARNING]: Tried to stop module aw-server, but it wasn't running  (aw_qt.manager:73)
```

**Comment by johan-bjareholt** [comment]
> OSError: [Errno 99] Cannot assign requested address

Seems like something is already running on the default aw-server port? (5600) Probably another instance of aw-server?
Make sure no instances of aw-server is already running when starting aw-qt. You can see if aw-server is running by trying to access the dashboard directly by going to "127.0.0.1:5600" in your browser.

**Comment by ErikBjare** [comment]
Closing since @Titan-C never replied and @johan-bjareholt probably got the answer right.
