### ISSUE TITLE
aw-server crashes on startup macos after updating

### ISSUE THREAD

**Issue by exoji2e** [ActivityWatch/activitywatch#168]
I just updated by doing the following:
```
#!/bin/bash
git pull
git submodule update --init --recursive
source ~/repos/activitywatch/venv/bin/activate
make build
```
Now when I'm running aw-qt, I get the following import error:
```
#!/bin/bash
source ~/repos/activitywatch/venv/bin/activate
aw-qt
```
```
exoji2e@Charizard ~/r/activitywatch> ./run_activity_watch.sh
2018-01-23 14:31:25 [INFO ]: Starting module aw-server  (aw_qt.manager:46)
2018-01-23 14:31:25 [INFO ]: Starting module aw-watcher-window  (aw_qt.manager:46)
2018-01-23 14:31:25 [INFO ]: Starting module aw-watcher-afk  (aw_qt.manager:46)
2018-01-23 14:31:25 [INFO ]: Creating trayicon...  (aw_qt.trayicon:150)
2018-01-23 14:31:25 [INFO ]: Running watcher with poll time 1.0 seconds  (aw_watcher_window.main:35)
2018-01-23 14:31:25 [INFO ]: aw-watcher-window has started  (aw_watcher_window.main:44)
Traceback (most recent call last):
  File "/Users/exoji2e/repos/activitywatch/venv/bin/aw-server", line 11, in <module>
    load_entry_point('aw-server==0.1', 'console_scripts', 'aw-server')()
  File "/Users/exoji2e/repos/activitywatch/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/exoji2e/repos/activitywatch/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/Users/exoji2e/repos/activitywatch/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/Users/exoji2e/repos/activitywatch/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/exoji2e/repos/activitywatch/venv/lib/python3.6/site-packages/aw_server/__init__.py", line 5, in <module>
    from .server import app
  File "/Users/exoji2e/repos/activitywatch/venv/lib/python3.6/site-packages/aw_server/server.py", line 10, in <module>
    from .api import ServerAPI
  File "/Users/exoji2e/repos/activitywatch/venv/lib/python3.6/site-packages/aw_server/api.py", line 9, in <module>
    from aw_core import transforms, views
ImportError: cannot import name 'transforms'
/Users/exoji2e/repos/activitywatch/venv/lib/python3.6/site-packages/aw_watcher_afk/afk.py:44: DeprecationWarning: Call to deprecated function setup_bucket, this warning will only show once per function.
  self.client.setup_bucket(self.bucketname, eventtype)
2018-01-23 14:31:25 [INFO ]: afkwatcher started  (aw_watcher_afk.afk:55)
2018-01-23 14:31:27 [WARNING]: Tried to stop module aw-server, but it wasn't running  (aw_qt.manager:73)
```

I can look into aw_core, and there is a module transforms there, so it seems that it doesn't load the correct version of aw_core after?

**Comment by ErikBjare** [comment]
Try this branch: https://github.com/ActivityWatch/activitywatch/pull/165

**Comment by exoji2e** [comment]
Cool, that branch works for me :)
