### ISSUE TITLE
Error trying to execute pre-built aw-qt on Ubuntu 17.10

### ISSUE THREAD

**Issue by temrix** [ActivityWatch/activitywatch#171]
I get this error when trying to run `aw-qt` v0.7.1:

```
$ ./aw-qt 
Traceback (most recent call last):
  File "aw_qt/__main__.py", line 1, in <module>
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "aw_qt/__init__.py", line 3, in <module>
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "aw_qt/main.py", line 9, in <module>
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "aw_qt/trayicon.py", line 9, in <module>
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
ImportError: /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1: undefined symbol: drmGetDevices2
[2760] Failed to execute script __main__
```

It is some weird behavior with this Ubuntu release as I have had some issues with libGL before. I would appreciate it if you could point me in the right direction which package may be missing.

**Comment by ErikBjare** [comment]
This is indeed a weird bug, but there is a workaround here: https://github.com/ActivityWatch/activitywatch/issues/161#issuecomment-360831342

In a future release this workaround will be the default.
