### ISSUE TITLE
Error while running from prebuilt package

### ISSUE THREAD

**Issue by mzfr** [ActivityWatch/activitywatch#177]
I'm running ActivityWatch from prebuilt packages and when I run `./aw-qt`, I am getting the following error:
```
Traceback (most recent call last):
  File "aw_qt/__main__.py", line 1, in <module>
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "aw_qt/__init__.py", line 3, in <module>
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "aw_qt/main.py", line 9, in <module>
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "aw_qt/trayicon.py", line 9, in <module>
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
ImportError: /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1: undefined symbol: drmGetDevices2
[6812] Failed to execute script __main__
```

**Comment by ErikBjare** [comment]
Sorry about this, should be resolved in the next major release but until then there is a workaround here: https://github.com/ActivityWatch/activitywatch/issues/161#issuecomment-360831342
