### ISSUE TITLE
Module aw-server quit unexpectedly

### ISSUE THREAD

**Issue by Almin17** [ActivityWatch/activitywatch#206]
Hey guys,

First of all thanks for the amazing application!
I sadly have a specific recurring problem with the start of the aw-server.

![awserverquit](https://user-images.githubusercontent.com/8478871/41772374-af79b0b2-7618-11e8-806c-a2996055f385.png)

On the commandline it looks like follows:

```
[me@mypc ~]$ aw-server 
fatal: Kein Git-Repository (oder irgendeines der Elternverzeichnisse): .git
Unable to get current commit with git
2018-06-22 12:26:51 [INFO ]: Using storage method: peewee  (aw_server.main:26)
2018-06-22 12:26:51 [INFO ]: Starting up...  (aw_server.main:31)
2018-06-22 12:26:51 [INFO ]: Using database file: /home/me/.local/share/activitywatch/aw-server/peewee-sqlite.v2.db  (aw_datastore.storages.peewee:111)
 * Serving Flask app "aw-server" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
2018-06-22 12:26:51 [ERROR]: [Errno 98] Address already in use  (aw_server.server:75)
Traceback (most recent call last):
  File "__main__.py", line 3, in <module>
  File "aw_server/main.py", line 33, in main
  File "aw_server/server.py", line 76, in _start
  File "aw_server/server.py", line 73, in _start
  File "site-packages/flask/app.py", line 943, in run
  File "site-packages/werkzeug/serving.py", line 814, in run_simple
  File "site-packages/werkzeug/serving.py", line 774, in inner
  File "site-packages/werkzeug/serving.py", line 660, in make_server
  File "site-packages/werkzeug/serving.py", line 577, in __init__
  File "socketserver.py", line 440, in __init__
  File "http/server.py", line 138, in server_bind
  File "socketserver.py", line 454, in server_bind
OSError: [Errno 98] Address already in use
[11159] Failed to execute script __main__
[me@mypc ~]$ 
```

I installed it on Arch through the Arch User Repository.
aur/activitywatch-bin 0.8.0b3-2

Is there any way I can help getting this issue fixed?

The corresponding log contains:
```
[me@mypc ~]$ cat ~/.cache/activitywatch/log/aw-server/aw-server_2018-06-22T12-31-41.log 
2018-06-22 12:31:41 [INFO ]: Using storage method: peewee  (aw_server.main:26)
2018-06-22 12:31:41 [INFO ]: Starting up...  (aw_server.main:31)
2018-06-22 12:31:41 [INFO ]: Using database file: /home/me/.local/share/activitywatch/aw-server/peewee-sqlite.v2.db  (aw_datastore.storages.peewee:111)
2018-06-22 12:31:41 [ERROR]: [Errno 98] Address already in use  (aw_server.server:75)
[me@mypc ~]$ 
```

**Comment by Otto-AA** [comment]
_Disclaimer: I haven't worked with aw-server.py yet and I'm definitely no expert on this_

> [Errno 98] Address already in use (aw_server.server:75)

This seems to happen when the port is already in use. So on startup, aw-server.py tries to create the server on port 5600, but due to some process already using it, it fails.

So, based on [this SO answer](https://stackoverflow.com/a/7706873) I'd suggest you to look up which process is using this port by running `lsof -i :5600` and (if it doesn't seem important) kill it with `kill 1234567` (enter the process number instead of 1234567). 

Then it should hopefully work by restarting the server :)

**Comment by ErikBjare** [comment]
This is commonly an issue when aw-server, or another application, is already using port 5600. @Otto-AA's answer should help.

**Comment by CyberIntelSystems** [comment]
Port 5600 may also be used by HNS.
Run this `Restart-Service hns -f` with PowerShell (Admin) to release the port.
