### ISSUE TITLE
aw-watcher-afk ValueError: paramflags must have the same length as argtypes

### ISSUE THREAD

**Issue by friuns2** [ActivityWatch/activitywatch#210]
version activitywatch-v0.8.0b3-windows-x86_64.zip
**Fails with error**

aw-watcher-afk
2018-07-03 12:27:15 [INFO ]: aw-watcher-afk started  (aw_watcher_afk.afk:53)
2018-07-03 12:27:17 [INFO ]: Connection to aw-server established by aw-watcher-a
Traceback (most recent call last):
  File "aw_watcher_afk\__main__.py", line 31, in <module>
  File "aw_watcher_afk\__main__.py", line 28, in main
  File "aw_watcher_afk\afk.py", line 63, in run
  File "aw_watcher_afk\afk.py", line 77, in heartbeat_loop
  File "aw_watcher_afk\windows.py", line 34, in seconds_since_last_input
  File "aw_watcher_afk\windows.py", line 18, in _getLastInputTick
ValueError: paramflags must have the same length as argtypes
[48884] Failed to execute script __main__

**Comment by johan-bjareholt** [comment]
Alright, closing this.

If I have time tonight I might get a windows VM up and running and try to debug this once and for all.

**Comment by ErikBjare** [comment]
@friuns2 That was some much-needed output. I think I can push a fix without having to boot into Windows. Thanks!
