### ISSUE TITLE
v0.8.0b4 broke aw-qt

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#211]
Installed from AUR, `aw-server` and `aw-watcher-*` works fine.

```
Traceback (most recent call last):
  File "aw_qt/__main__.py", line 1, in <module>
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "aw_qt/__init__.py", line 1, in <module>
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "aw_qt/resources.py", line 9, in <module>
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
ImportError: No module named 'PyQt5.sip'
[22338] Failed to execute script __main__
```

Might be related to the new version of PyQt5: https://github.com/ActivityWatch/activitywatch/issues/199#issuecomment-402252639

Downgraded the AUR package for now.

**Comment by ErikBjare** [comment]
Verified fixed in https://github.com/ActivityWatch/activitywatch/releases/tag/v0.8.0b5

Just pushed a new AUR version.
