### ISSUE TITLE
Warning: gap of negative duration

### ISSUE THREAD

**Issue by MatthewScholefield** [ActivityWatch/activitywatch#239]
Not sure what this means, but it floods the logs when running aw-server:
```
2018-09-23 23:37:59 [WARNING]: Gap was of negative duration (-6.016s). This error will only show once per batch.  (aw_transform.flood:28)
2018-09-23 23:38:25 [WARNING]: Gap was of negative duration (-6.016s). This error will only show once per batch.  (aw_transform.flood:28)
2018-09-23 23:38:54 [WARNING]: Gap was of negative duration (-6.016s). This error will only show once per batch.  (aw_transform.flood:28)
```

**Comment by johan-bjareholt** [comment]
@ErikBjare I have seen this lots of times aswell (on almost all query requests).
Do you have any idea why it is occuring, is there some specific watcher which creates events which intersects that you know of?

**Comment by ErikBjare** [comment]
@johan-bjareholt This occurs when events overlap. We would have to investigate which watcher is causing it.

**Comment by jasonszang** [comment]
Also encountering this issue. 
And it seems that when this warning is flooding the log the statistics also becomes incorrect. It looks like that the server failed to process events. All statistics stopped to grow.
I'm using AW on windows with v0.8.0b6 binary release and Firefox watcher plugin.

**Comment by slang800** [comment]
I'm getting the same type of messages:

```
WARNING:aw_transform.flood:Gap was of negative duration but could be safely merged (-2224.419s). This message will only show once per batch.
2019-07-27 14:29:00 [WARNING]: Gap was of negative duration but could be safely merged (-2224.419s). This message will only show once per batch.  (aw_transform.flood:45)
WARNING:aw_transform.flood:Gap was of negative duration and could NOT be safely merged (-535.887s). This warning will only show once per batch.
2019-07-27 14:29:00 [WARNING]: Gap was of negative duration and could NOT be safely merged (-535.887s). This warning will only show once per batch.  (aw_transform.flood:49)
WARNING:aw_transform.flood:Gap was of negative duration but could be safely merged (-425.637s). This message will only show once per batch.
2019-07-27 14:29:00 [WARNING]: Gap was of negative duration but could be safely merged (-425.637s). This message will only show once per batch.  (aw_transform.flood:45)
WARNING:aw_transform.flood:Gap was of negative duration and could NOT be safely merged (-1252.44s). This warning will only show once per batch.
2019-07-27 14:29:00 [WARNING]: Gap was of negative duration and could NOT be safely merged (-1252.44s). This warning will only show once per batch.  (aw_transform.flood:49)
WARNING:aw_transform.flood:Gap was of negative duration but could be safely merged (-5295.763s). This message will only show once per batch.
2019-07-27 14:29:00 [WARNING]: Gap was of negative duration but could be safely merged (-5295.763s). This message will only show once per batch.  (aw_transform.flood:45)
WARNING:aw_transform.flood:Gap was of negative duration but could be safely merged (-34205.837s). This message will only show once per batch.
2019-07-27 14:29:00 [WARNING]: Gap was of negative duration but could be safely merged (-34205.837s). This message will only show once per batch.  (aw_transform.flood:45)
WARNING:aw_transform.flood:Gap was of negative duration and could NOT be safely merged (-550.956s). This warning will only show once per batch.
2019-07-27 14:29:00 [WARNING]: Gap was of negative duration and could NOT be safely merged (-550.956s). This warning will only show once per batch.  (aw_transform.flood:49)
WARNING:aw_transform.flood:Gap was of negative duration but could be safely merged (-290.371s). This message will only show once per batch.
2019-07-27 14:29:00 [WARNING]: Gap was of negative duration but could be safely merged (-290.371s). This message will only show once per batch.  (aw_transform.flood:45)
WARNING:aw_transform.flood:Gap was of negative duration and could NOT be safely merged (-315.507s). This warning will only show once per batch.
2019-07-27 14:29:00 [WARNING]: Gap was of negative duration and could NOT be safely merged (-315.507s). This warning will only show once per batch.  (aw_transform.flood:49)
WARNING:aw_transform.flood:Gap was of negative duration but could be safely merged (-165.214s). This message will only show once per batch.
2019-07-27 14:29:00 [WARNING]: Gap was of negative duration but could be safely merged (-165.214s). This message will only show once per batch.  (aw_transform.flood:45)
WARNING:aw_transform.flood:Gap was of negative duration but could be safely merged (-717.051s). This message will only show once per batch.
2019-07-27 14:29:00 [WARNING]: Gap was of negative duration but could be safely merged (-717.051s). This message will only show once per batch.  (aw_transform.flood:45)
WARNING:aw_transform.flood:Gap was of negative duration but could be safely merged (-717.051s). This message will only show once per batch.
2019-07-27 14:29:02 [WARNING]: Gap was of negative duration but could be safely merged (-717.051s). This message will only show once per batch.  (aw_transform.flood:45)
```

It would be really nice if it told me which watcher these events were coming from.

**Comment by wasinix** [comment]
I can reproduce this error, when I try to change the default "Categorization" rules.

As soon I change something there and save it, I get error 400 in the activity tab of the dashboard and find the "Gap was of negative duration" errors in the server log.
It is enough changing the existing category Work from RegEx to "No Rule".

When changing categorization rules back to default, the error is gone.

Version used: 0.8.3. @ Windows 10

**Comment by ErikBjare** [comment]
@wasinix The error you get is unrelated to this warning. A fix has been merged and it will be working in the next release: https://github.com/ActivityWatch/activitywatch/issues/313

**Comment by the-architech** [comment]
I am also getting these errors. My best guess is that the watchers cache the events while either the server is offline, or if the watchers were stopped then started, and the events they are trying to publish to the server are not matching the time stamp of the server. Which may explain the negative time  

The warning messages go longer based on how long the server has not received communication from watchers or the watchers have not communicated with the server. I am not sure how the time is kept on the server and how the watchers track time but it is likely due to the mismatch of timing.

**Comment by johan-bjareholt** [comment]
> My best guess is that the watchers cache the events while either the server is offline, or if the watchers were stopped then started, and the events they are trying to publish to the server are not matching the time stamp of the server. Which may explain the negative time

A good hypothesis, but it's not possible as event timestamps are saved before they are potentially queued up to be sent to the server so that cannot be the issue. The servers clock is always irrelevant. 

It would be pretty easy to find which bucket makes this issue is we just do a query with a flood transform to each one of them, I might try this later.

**Comment by ErikBjare** [comment]
Someone mentioned this in the Discord yesterday:

![image](https://user-images.githubusercontent.com/1405370/115006284-fe1deb00-9ea8-11eb-969c-6be430ae08e3.png)

Looks like the issue might be in aw-watcher-afk.

**Comment by JoseEchave** [comment]
> Someone mentioned this in the Discord today:
> 
> ![image](https://user-images.githubusercontent.com/1405370/115006284-fe1deb00-9ea8-11eb-969c-6be430ae08e3.png)
> 
> Looks like the issue might be in aw-watcher-afk.

Hi I have removed the duplicated, and then compared the data frames of the events, the duplicated events were mainly from the aw-watcher-afk watcher
![image](https://user-images.githubusercontent.com/47890124/115012640-c028c300-9eb8-11eb-9c22-feb40835888b.png)

And out of those the majority are afk events
![image](https://user-images.githubusercontent.com/47890124/115012740-dc2c6480-9eb8-11eb-96a5-b23933f311f8.png)

Also, those duplications happened more in my work computer where I use VPN (not sure if that might be the reason though)
![image](https://user-images.githubusercontent.com/47890124/115012891-0716b880-9eb9-11eb-9ca2-093da6f149b2.png)

I hope this helps you somehow with the debugging

Thanks team for the wonderful tool you have created!

**Comment by daobrien** [comment]
What's the latest with this? It's been open for nearly 6 years and I still get these messages.
~~~
2024-05-30 13:48:54 [INFO ]: Received heartbeat after pulse window, inserting as new event. (bucket: aw-watcher-afk_galaxy.milky.way)  (aw_server.api:279)
2024-05-30 13:48:59 [WARNING]: Gap was of negative duration but could be safely merged (-336.987s). This message will only show once per batch.  (aw_transform.flood:46)
2024-05-30 13:48:59 [WARNING]: Gap was of negative duration but could be safely merged (-504.166s). This message will only show once per batch.  (aw_transform.flood:46)
2024-05-30 13:48:59 [WARNING]: Gap was of negative duration but could be safely merged (-1201.106s). This message will only show once per batch.  (aw_transform.flood:46)
~~~
and many more besides.
thanks

**Comment by patienttruth** [comment]
> [johan-bjareholt](https://github.com/johan-bjareholt) This occurs when events overlap. We would have to investigate which watcher is causing it.

@ErikBjare 

I just had this show up after I added the Chrome Extension watcher. It worked for a few minutes, then as I was setting up categories I started getting a `something null` error in the UI (sorry I didn't collect it). I checked logs and found the message which brought me to this issue. I deleted the `aw-watcher-web-brave_` bucket, and after the extension reconnected the errors went away.

<details><summary>.log</summary>

```
2026-07-02 11:43:48 [INFO ]: Using storage method: peewee  (aw_server.main:33)
2026-07-02 11:43:48 [INFO ]: Starting up...  (aw_server.main:41)
2026-07-02 11:43:48 [INFO ]: Using database file: C:\Users\Evan\AppData\Local\activitywatch\activitywatch\aw-server\peewee-sqlite.v2.db  (aw_datastore.storages.peewee:150)
2026-07-02 11:43:48 [INFO ]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://localhost:5600  (werkzeug:187)
2026-07-02 11:43:48 [INFO ]: [33mPress CTRL+C to quit[0m  (werkzeug:187)
2026-07-02 11:43:57 [INFO ]: 400 (127.0.0.1): [31m[1mPOST /api/0/query/ HTTP/1.1[0m  (flask:25)
2026-07-02 11:44:05 [WARNING]: Gap was of negative duration but could be safely merged (-17734.053s). This message will only show once per batch.  (aw_transform.flood:46)
2026-07-02 11:44:05 [WARNING]: Gap was of negative duration and could NOT be safely merged (-287.741s). This warning will only show once per batch.  (aw_transform.flood:52)
2026-07-02 11:44:05 [INFO ]: 400 (127.0.0.1): [31m[1mPOST /api/0/query/ HTTP/1.1[0m  (flask:25)
2026-07-02 11:45:04 [WARNING]: Gap was of negative duration but could be safely merged (-17734.053s). This message will only show once per batch.  (aw_transform.flood:46)
2026-07-02 11:45:04 [WARNING]: Gap was of negative duration and could NOT be safely merged (-287.741s). This warning will only show once per batch.  (aw_transform.flood:52)
2026-07-02 11:45:05 [INFO ]: 400 (127.0.0.1): [31m[1mPOST /api/0/query/ HTTP/1.1[0m  (flask:25)
2026-07-02 11:45:07 [INFO ]: Received heartbeat after pulse window, inserting as new event. (bucket: aw-watcher-web-brave_HOST)  (aw_server.api:317)
2026-07-02 11:45:42 [WARNING]: Gap was of negative duration but could be safely merged (-0.004s). This message will only show once per batch.  (aw_transform.flood:46)
2026-07-02 11:45:42 [WARNING]: Gap was of negative duration and could NOT be safely merged (-323.085s). This warning will only show once per batch.  (aw_transform.flood:52)
2026-07-02 11:45:42 [INFO ]: 400 (127.0.0.1): [31m[1mPOST /api/0/query/ HTTP/1.1[0m  (flask:25)
2026-07-02 11:45:44 [WARNING]: Gap was of negative duration but could be safely merged (-19718.344s). This message will only show once per batch.  (aw_transform.flood:46)
2026-07-02 11:45:44 [WARNING]: Gap was of negative duration and could NOT be safely merged (-19718.344s). This warning will only show once per batch.  (aw_transform.flood:52)
2026-07-02 11:45:44 [INFO ]: 400 (127.0.0.1): [31m[1mPOST /api/0/query/ HTTP/1.1[0m  (flask:25)
2026-07-02 11:45:50 [WARNING]: Gap was of negative duration but could be safely merged (-19718.344s). This message will only show once per batch.  (aw_transform.flood:46)
2026-07-02 11:45:50 [WARNING]: Gap was of negative duration and could NOT be safely merged (-19718.344s). This warning will only show once per batch.  (aw_transform.flood:52)
2026-07-02 11:45:50 [INFO ]: 400 (127.0.0.1): [31m[1mPOST /api/0/query/ HTTP/1.1[0m  (flask:25)
2026-07-02 11:45:54 [WARNING]: Gap was of negative duration but could be safely merged (-19718.344s). This message will only show once per batch.  (aw_transform.flood:46)
2026-07-02 11:45:54 [WARNING]: Gap was of negative duration and could NOT be safely merged (-19718.344s). This warning will only show once per batch.  (aw_transform.flood:52)
2026-07-02 11:45:54 [INFO ]: 400 (127.0.0.1): [31m[1mPOST /api/0/query/ HTTP/1.1[0m  (flask:25)
2026-07-02 11:46:37 [INFO ]: Received heartbeat after pulse window, inserting as new event. (bucket: aw-watcher-web-brave_HOST)  (aw_server.api:317)
2026-07-02 11:47:10 [WARNING]: Gap was of negative duration but could be safely merged (-0.004s). This message will only show once per batch.  (aw_transform.flood:46)
2026-07-02 11:47:10 [WARNING]: Gap was of negative duration and could NOT be safely merged (-323.085s). This warning will only show once per batch.  (aw_transform.flood:52)
2026-07-02 11:47:10 [INFO ]: 400 (127.0.0.1): [31m[1mPOST /api/0/query/ HTTP/1.1[0m  (flask:25)
2026-07-02 11:47:57 [INFO ]: Deleting bucket 'aw-watcher-web-brave_HOST'  (aw_datastore.datastore.Datastore:70)
2026-07-02 11:48:03 [WARNING]: Gap was of negative duration but could be safely merged (-0.004s). This message will only show once per batch.  (aw_transform.flood:46)
2026-07-02 11:48:03 [WARNING]: Gap was of negative duration and could NOT be safely merged (-323.085s). This warning will only show once per batch.  (aw_transform.flood:52)
2026-07-02 11:48:05 [WARNING]: Gap was of negative duration but could be safely merged (-0.004s). This message will only show once per batch.  (aw_transform.flood:46)
2026-07-02 11:48:05 [WARNING]: Gap was of negative duration and could NOT be safely merged (-323.085s). This warning will only show once per batch.  (aw_transform.flood:52)
2026-07-02 11:48:05 [WARNING]: Gap was of negative duration but could be safely merged (-1596.155s). This message will only show once per batch.  (aw_transform.flood:46)
2026-07-02 11:48:05 [WARNING]: Gap was of negative duration but could be safely merged (-97.453s). This message will only show once per batch.  (aw_transform.flood:46)
2026-07-02 11:48:07 [WARNING]: Gap was of negative duration but could be safely merged (-423.664s). This message will only show once per batch.  (aw_transform.flood:46)
2026-07-02 11:48:07 [INFO ]: 404 (127.0.0.1): [33mPOST /api/0/buckets/aw-watcher-web-brave_HOST/heartbeat?pulsetime=80 HTTP/1.1[0m  (flask:25)
2026-07-02 11:48:07 [INFO ]: 404 (127.0.0.1): [33mPOST /api/0/buckets/aw-watcher-web-brave_HOST/heartbeat?pulsetime=80 HTTP/1.1[0m  (flask:25)
2026-07-02 11:48:07 [INFO ]: Creating bucket 'aw-watcher-web-brave_HOST'  (aw_datastore.datastore.Datastore:59)
2026-07-02 11:48:08 [WARNING]: Gap was of negative duration but could be safely merged (-768.016s). This message will only show once per batch.  (aw_transform.flood:46)
2026-07-02 11:48:08 [ERROR]: Exception on /api/0/buckets/aw-watcher-web-brave_HOST/heartbeat [POST]  (aw-server:1414)
Traceback (most recent call last):
  File "peewee.py", line 7285, in get
  File "peewee.py", line 4581, in __getitem__
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask\app.py", line 1484, in full_dispatch_request
  File "flask\app.py", line 1469, in dispatch_request
  File "aw_server\rest.py", line 45, in decorator
  File "flask_restx\api.py", line 404, in wrapper
  File "flask\views.py", line 109, in view
  File "flask_restx\resource.py", line 46, in dispatch_request
  File "aw_server\rest.py", line 300, in post
  File "aw_server\api.py", line 46, in g
  File "aw_server\api.py", line 314, in heartbeat
  File "aw_datastore\datastore.py", line 186, in replace_last
  File "aw_datastore\storages\peewee.py", line 294, in replace_last
  File "aw_datastore\storages\peewee.py", line 287, in _get_last
  File "peewee.py", line 7288, in get
aw_datastore.storages.peewee.EventModelDoesNotExist: <Model: EventModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."bucket_id", "t1"."timestamp", "t1"."duration", "t1"."datastr" FROM "eventmodel" AS "t1" WHERE ("t1"."bucket_id" = ?) ORDER BY "t1"."timestamp" DESC LIMIT ? OFFSET ?
Params: [4, 1, 0]
2026-07-02 11:48:08 [INFO ]: 500 (127.0.0.1): [35m[1mPOST /api/0/buckets/aw-watcher-web-brave_HOST/heartbeat?pulsetime=80 HTTP/1.1[0m  (flask:25)
2026-07-02 11:48:08 [ERROR]: Exception on /api/0/buckets/aw-watcher-web-brave_HOST/heartbeat [POST]  (aw-server:1414)
Traceback (most recent call last):
  File "peewee.py", line 7285, in get
  File "peewee.py", line 4581, in __getitem__
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask\app.py", line 1484, in full_dispatch_request
  File "flask\app.py", line 1469, in dispatch_request
  File "aw_server\rest.py", line 45, in decorator
  File "flask_restx\api.py", line 404, in wrapper
  File "flask\views.py", line 109, in view
  File "flask_restx\resource.py", line 46, in dispatch_request
  File "aw_server\rest.py", line 300, in post
  File "aw_server\api.py", line 46, in g
  File "aw_server\api.py", line 314, in heartbeat
  File "aw_datastore\datastore.py", line 186, in replace_last
  File "aw_datastore\storages\peewee.py", line 294, in replace_last
  File "aw_datastore\storages\peewee.py", line 287, in _get_last
  File "peewee.py", line 7288, in get
aw_datastore.storages.peewee.EventModelDoesNotExist: <Model: EventModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."bucket_id", "t1"."timestamp", "t1"."duration", "t1"."datastr" FROM "eventmodel" AS "t1" WHERE ("t1"."bucket_id" = ?) ORDER BY "t1"."timestamp" DESC LIMIT ? OFFSET ?
Params: [4, 1, 0]
2026-07-02 11:48:08 [INFO ]: 500 (127.0.0.1): [35m[1mPOST /api/0/buckets/aw-watcher-web-brave_HOST/heartbeat?pulsetime=80 HTTP/1.1[0m  (flask:25)
2026-07-02 11:48:08 [WARNING]: Gap was of negative duration but could be safely merged (-3600.001s). This message will only show once per batch.  (aw_transform.flood:46)
2026-07-02 11:48:09 [WARNING]: Gap was of negative duration but could be safely merged (-3600.001s). This message will only show once per batch.  (aw_transform.flood:46)
2026-07-02 11:48:09 [WARNING]: Gap was of negative duration but could be safely merged (-3600.001s). This message will only show once per batch.  (aw_transform.flood:46)
2026-07-02 11:48:09 [WARNING]: Gap was of negative duration but could be safely merged (-3600.001s). This message will only show once per batch.  (aw_transform.flood:46)
2026-07-02 11:48:09 [WARNING]: Gap was of negative duration but could be safely merged (-3600.001s). This message will only show once per batch.  (aw_transform.flood:46)
2026-07-02 11:48:09 [WARNING]: Gap was of negative duration but could be safely merged (-3600.001s). This message will only show once per batch.  (aw_transform.flood:46)
2026-07-02 11:48:10 [ERROR]: Exception on /api/0/buckets/aw-watcher-web-brave_HOST/heartbeat [POST]  (aw-server:1414)
Traceback (most recent call last):
  File "peewee.py", line 7285, in get
  File "peewee.py", line 4581, in __getitem__
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask\app.py", line 1484, in full_dispatch_request
  File "flask\app.py", line 1469, in dispatch_request
  File "aw_server\rest.py", line 45, in decorator
  File "flask_restx\api.py", line 404, in wrapper
  File "flask\views.py", line 109, in view
  File "flask_restx\resource.py", line 46, in dispatch_request
  File "aw_server\rest.py", line 300, in post
  File "aw_server\api.py", line 46, in g
  File "aw_server\api.py", line 314, in heartbeat
  File "aw_datastore\datastore.py", line 186, in replace_last
  File "aw_datastore\storages\peewee.py", line 294, in replace_last
  File "aw_datastore\storages\peewee.py", line 287, in _get_last
  File "peewee.py", line 7288, in get
aw_datastore.storages.peewee.EventModelDoesNotExist: <Model: EventModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."bucket_id", "t1"."timestamp", "t1"."duration", "t1"."datastr" FROM "eventmodel" AS "t1" WHERE ("t1"."bucket_id" = ?) ORDER BY "t1"."timestamp" DESC LIMIT ? OFFSET ?
Params: [4, 1, 0]
2026-07-02 11:48:10 [INFO ]: 500 (127.0.0.1): [35m[1mPOST /api/0/buckets/aw-watcher-web-brave_HOST/heartbeat?pulsetime=80 HTTP/1.1[0m  (flask:25)
2026-07-02 11:48:10 [ERROR]: Exception on /api/0/buckets/aw-watcher-web-brave_HOST/heartbeat [POST]  (aw-server:1414)
Traceback (most recent call last):
  File "peewee.py", line 7285, in get
  File "peewee.py", line 4581, in __getitem__
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask\app.py", line 1484, in full_dispatch_request
  File "flask\app.py", line 1469, in dispatch_request
  File "aw_server\rest.py", line 45, in decorator
  File "flask_restx\api.py", line 404, in wrapper
  File "flask\views.py", line 109, in view
  File "flask_restx\resource.py", line 46, in dispatch_request
  File "aw_server\rest.py", line 300, in post
  File "aw_server\api.py", line 46, in g
  File "aw_server\api.py", line 314, in heartbeat
  File "aw_datastore\datastore.py", line 186, in replace_last
  File "aw_datastore\storages\peewee.py", line 294, in replace_last
  File "aw_datastore\storages\peewee.py", line 287, in _get_last
  File "peewee.py", line 7288, in get
aw_datastore.storages.peewee.EventModelDoesNotExist: <Model: EventModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."bucket_id", "t1"."timestamp", "t1"."duration", "t1"."datastr" FROM "eventmodel" AS "t1" WHERE ("t1"."bucket_id" = ?) ORDER BY "t1"."timestamp" DESC LIMIT ? OFFSET ?
Params: [4, 1, 0]
2026-07-02 11:48:10 [INFO ]: 500 (127.0.0.1): [35m[1mPOST /api/0/buckets/aw-watcher-web-brave_HOST/heartbeat?pulsetime=80 HTTP/1.1[0m  (flask:25)
2026-07-02 11:48:14 [ERROR]: Exception on /api/0/buckets/aw-watcher-web-brave_HOST/heartbeat [POST]  (aw-server:1414)
Traceback (most recent call last):
  File "peewee.py", line 7285, in get
  File "peewee.py", line 4581, in __getitem__
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask\app.py", line 1484, in full_dispatch_request
  File "flask\app.py", line 1469, in dispatch_request
  File "aw_server\rest.py", line 45, in decorator
  File "flask_restx\api.py", line 404, in wrapper
  File "flask\views.py", line 109, in view
  File "flask_restx\resource.py", line 46, in dispatch_request
  File "aw_server\rest.py", line 300, in post
  File "aw_server\api.py", line 46, in g
  File "aw_server\api.py", line 314, in heartbeat
  File "aw_datastore\datastore.py", line 186, in replace_last
  File "aw_datastore\storages\peewee.py", line 294, in replace_last
  File "aw_datastore\storages\peewee.py", line 287, in _get_last
  File "peewee.py", line 7288, in get
aw_datastore.storages.peewee.EventModelDoesNotExist: <Model: EventModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."bucket_id", "t1"."timestamp", "t1"."duration", "t1"."datastr" FROM "eventmodel" AS "t1" WHERE ("t1"."bucket_id" = ?) ORDER BY "t1"."timestamp" DESC LIMIT ? OFFSET ?
Params: [4, 1, 0]
2026-07-02 11:48:14 [INFO ]: 500 (127.0.0.1): [35m[1mPOST /api/0/buckets/aw-watcher-web-brave_HOST/heartbeat?pulsetime=80 HTTP/1.1[0m  (flask:25)
2026-07-02 11:48:14 [ERROR]: Exception on /api/0/buckets/aw-watcher-web-brave_HOST/heartbeat [POST]  (aw-server:1414)
Traceback (most recent call last):
  File "peewee.py", line 7285, in get
  File "peewee.py", line 4581, in __getitem__
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask\app.py", line 1484, in full_dispatch_request
  File "flask\app.py", line 1469, in dispatch_request
  File "aw_server\rest.py", line 45, in decorator
  File "flask_restx\api.py", line 404, in wrapper
  File "flask\views.py", line 109, in view
  File "flask_restx\resource.py", line 46, in dispatch_request
  File "aw_server\rest.py", line 300, in post
  File "aw_server\api.py", line 46, in g
  File "aw_server\api.py", line 314, in heartbeat
  File "aw_datastore\datastore.py", line 186, in replace_last
  File "aw_datastore\storages\peewee.py", line 294, in replace_last
  File "aw_datastore\storages\peewee.py", line 287, in _get_last
  File "peewee.py", line 7288, in get
aw_datastore.storages.peewee.EventModelDoesNotExist: <Model: EventModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."bucket_id", "t1"."timestamp", "t1"."duration", "t1"."datastr" FROM "eventmodel" AS "t1" WHERE ("t1"."bucket_id" = ?) ORDER BY "t1"."timestamp" DESC LIMIT ? OFFSET ?
Params: [4, 1, 0]
2026-07-02 11:48:14 [INFO ]: 500 (127.0.0.1): [35m[1mPOST /api/0/buckets/aw-watcher-web-brave_HOST/heartbeat?pulsetime=80 HTTP/1.1[0m  (flask:25)
2026-07-02 11:53:07 [INFO ]: Received heartbeat after pulse window, inserting as new event. (bucket: aw-watcher-web-brave_HOST)  (aw_server.api:317)

``` 
</details>
