### ISSUE TITLE
Unable to start modules (corrupted config files)

### ISSUE THREAD

**Issue by nicolae-stroncea** [ActivityWatch/activitywatch#245]
One Week ago, the activitywatch suddenly stopped recording data. I wasn't making any changes to the source at the time, so I don't' know what triggered it. Here are the errors:

```
  File "C:\users\user\appdata\local\programs\python\python36-32\Scripts\aw-watcher-window-script.py", line 11, in <module>
    load_entry_point('aw-watcher-window==0.2', 'console_scripts', 'aw-watcher-window')()
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\aw_watcher_window\main.py", line 29, in main
Traceback (most recent call last):
  File "C:\users\user\appdata\local\programs\python\python36-32\Scripts\aw-watcher-afk-script.py", line 11, in <module>
    load_entry_point('aw-watcher-afk==0.2', 'console_scripts', 'aw-watcher-afk')()
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 480, in load_entry_point
    config = load_config()
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\aw_watcher_window\config.py", line 18, in load_config
    return _load_config("aw-watcher-window", default_client_config)["aw-watcher-window"]
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\aw_core\config.py", line 23, in load_config
    config.read_file(f)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\configparser.py", line 718, in read_file
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2693, in load_entry_point
    self._read(f, source)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\configparser.py", line 1080, in _read
    return ep.load()
    raise MissingSectionHeaderError(fpname, lineno, line)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2324, in load
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'C:\\Users\\user\\AppData\\Local\\activitywatch\\activitywatch\\aw-watcher-window\\aw-watcher-window.ini', line: 1
'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
    return self.resolve()
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\aw_watcher_afk\__init__.py", line 1, in <module>
    from . import __main__
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\aw_watcher_afk\__main__.py", line 5, in <module>
    from aw_watcher_afk.afk import AFKWatcher
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\aw_watcher_afk\afk.py", line 10, in <module>
    from .config import watcher_config
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\aw_watcher_afk\config.py", line 16, in <module>
    watcher_config = load_config("aw-watcher-afk", default_config)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\aw_core\config.py", line 23, in load_config
    config.read_file(f)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\configparser.py", line 718, in read_file
    self._read(f, source)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\configparser.py", line 1080, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'C:\\Users\\user\\AppData\\Local\\activitywatch\\activitywatch\\aw-watcher-afk\\aw-watcher-afk.ini', line: 1
'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
2018-10-30 09:21:14 [WARNING]: Tried to stop module aw-watcher-afk, but it wasn't running  (aw_qt.manager:73)
2018-10-30 09:21:14 [WARNING]: Tried to stop module aw-watcher-window, but it wasn't running  (aw_qt.manager:73)
Traceback (most recent call last):
  File "C:\users\user\appdata\local\programs\python\python36-32\Scripts\aw-server-script.py", line 11, in <module>
    load_entry_point('aw-server===v0.8-dev-84f0f96', 'console_scripts', 'aw-server')()
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2324, in load
    return self.resolve()
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\aw_server\__init__.py", line 13, in <module>
    from .main import main
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\aw_server\main.py", line 7, in <module>
    from .config import config
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\aw_server\config.py", line 19, in <module>
    config = load_config("aw-server", default_config)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\aw_core\config.py", line 23, in load_config
    config.read_file(f)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\configparser.py", line 718, in read_file
    self._read(f, source)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\configparser.py", line 1080, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'C:\\Users\\user\\AppData\\Local\\activitywatch\\activitywatch\\aw-server\\aw-server.ini', line: 1
'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
2018-10-30 09:21:16 [WARNING]: Tried to stop module aw-server, but it wasn't running  (aw_qt.manager:73)
```

**Comment by ErikBjare** [comment]
Something clearly happened to your configuration files which seem to be filled with junk. Try removing them and restart.

**Comment by ErikBjare** [comment]
I think it's pretty obvious from the logs that something is wrong with your config files and not ActivityWatch itself (although it's not impossible your config files got corrupted *by* ActivityWatch I find it unlikely). Closing unless you have further issues.
