### ISSUE TITLE
Prebuilt package won't start on Ubuntu 16.04

### ISSUE THREAD

**Issue by panchoop** [ActivityWatch/activitywatch#268]
## Describe the bug
It won't run, arguing some permission error.

## To Reproduce
1.- Download zip activitywatch-v0.8.0b7-linux-x86_64.zip
2.- Unzip 
3.- open terminal and run "sudo ./aw-qt"
4.- Output:  PermissioError: [Errno 13] Permission denied

In detail: 
2019-01-24 10:52:51 [INFO ]: Starting module aw-server  (aw_qt.manager:46)
Traceback (most recent call last):
  File "aw_qt/__main__.py", line 3, in <module>
  File "aw_qt/main.py", line 19, in main
  File "aw_qt/manager.py", line 149, in autostart
  File "aw_qt/manager.py", line 142, in start
  File "aw_qt/manager.py", line 67, in start
  File "subprocess.py", line 676, in __init__
  File "subprocess.py", line 1289, in _execute_child
PermissionError: [Errno 13] Permission denied
[31414] Failed to execute script __main__

## Expected behavior
To run.

## Environment
 - ActivityWatch version: [e.g. v0.8.0b7]
 - OS: LinuxMint Sylvia 18.3, based on Ubuntu 16.04

**Comment by panchoop** [comment]
Hey ! Thank you for the incredibly fast answer! 

So, if I run without sudo, I got precisely the same error.

The issue was about unzipping. As far as I remembered, I think I mounted the zip and then copy-pasted into a folder. Now I tried again, by using the file manager and it worked! 

Thank you !

**Comment by ErikBjare** [comment]
@mizzunet Looks like you have `/root` in your `PATH`, why?

We should probably just emit a warning and not crash if it happens when looking, though: https://github.com/ActivityWatch/aw-qt/blob/eb707b2716c0c5750569da0732057d171531af7c/aw_qt/manager.py#L94

**Comment by ErikBjare** [comment]
@mizzunet I created a new issue to track that minor fix: https://github.com/ActivityWatch/activitywatch/issues/739

Locking this issue.
