### ISSUE TITLE
err at elifecycle

### ISSUE THREAD

**Issue by shri120kant** [ActivityWatch/activitywatch#280]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vis@4.21.0-SNAPSHOT build: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vis@4.21.0-SNAPSHOT build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/shri13/.npm/_logs/2019-02-23T21_33_13_844Z-debug.log
npm run build

**Comment by johan-bjareholt** [comment]
Full log not attached, please supply more info or we can't help you

**Comment by shri120kant** [comment]
found 18 vulnerabilities (2 low, 10 moderate, 5 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

> vis@4.21.0-SNAPSHOT build /home/shri13/activitywatch/aw-server/aw-webui/node_modules/vis
> gulp

[13:33:00] Using gulpfile ~/activitywatch/aw-server/aw-webui/node_modules/vis/gulpfile.js
[13:33:00] Starting 'clean'...
[13:33:00] Starting 'bundle-js'...
[13:33:00] Starting 'bundle-js-individual'...
[13:33:00] Starting 'bundle-css'...
[13:33:00] Starting 'bundle-css-individual'...
[13:33:01] Finished 'clean' after 384 ms
[13:33:01] Starting 'copy'...
[13:33:10] Error: vis-timeline-graph2d.min.js from UglifyJs
Unexpected token operator «=», expected punc «,» [vis-timeline-graph2d.min.js:216,54]
[13:33:10] Error: vis-graph3d.min.js from UglifyJs
Unexpected token operator «=», expected punc «,» [vis-graph3d.min.js:216,54]
[13:33:11] Finished 'bundle-css-individual' after 11 s
[13:33:11] Error: vis-network.min.js from UglifyJs
Unexpected token operator «=», expected punc «,» [vis-network.min.js:216,54]
[13:33:11] Finished 'bundle-js-individual' after 11 s
[13:33:13] Finished 'bundle-js' after 13 s
[13:33:13] Starting 'minify'...
[13:33:13] 'minify' errored after 73 ms
[13:33:13] SyntaxError: Unexpected token operator «=», expected punc «,»
    at JS_Parse_Error.get (eval at <anonymous> (/home/shri13/activitywatch/aw-server/aw-webui/node_modules/vis/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
    at formatError (/home/shri13/activitywatch/aw-server/aw-webui/node_modules/vis/node_modules/gulp/bin/gulp.js:165:18)
    at Gulp.<anonymous> (/home/shri13/activitywatch/aw-server/aw-webui/node_modules/vis/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:116:13)
    at Gulp.emit (events.js:211:7)
    at Gulp.Orchestrator._emitTaskDone (/home/shri13/activitywatch/aw-server/aw-webui/node_modules/vis/node_modules/orchestrator/index.js:264:8)
    at /home/shri13/activitywatch/aw-server/aw-webui/node_modules/vis/node_modules/orchestrator/index.js:275:23
    at finish (/home/shri13/activitywatch/aw-server/aw-webui/node_modules/vis/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/home/shri13/activitywatch/aw-server/aw-webui/node_modules/vis/node_modules/orchestrator/lib/runTask.js:36:10)
    at Gulp.Orchestrator._runTask (/home/shri13/activitywatch/aw-server/aw-webui/node_modules/vis/node_modules/orchestrator/index.js:273:3)
[13:33:13] Finished 'bundle-css' after 13 s
[13:33:13] Finished 'copy' after 13 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vis@4.21.0-SNAPSHOT build: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vis@4.21.0-SNAPSHOT build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/shri13/.npm/_logs/2019-02-23T21_33_13_844Z-debug.log
npm run build

> aw-webui@1.0.0 build /home/shri13/activitywatch/aw-server/aw-webui
> node build/build.js

  Tip:
  Built files are meant to be served over an HTTP server.
  Opening index.html over file:// won't work.

**Comment by johan-bjareholt** [comment]
Everything looks to be built correctly, the issue with the vis dependency is a known bug and doesn't impact functionality.
