### ISSUE TITLE
Random crash Win10

### ISSUE THREAD

**Issue by pcuci** [ActivityWatch/activitywatch#288]
AW shuts down after a while, then I can't bring it back up by hand (seems to work on initial startup, I'm on Win 10, aw v0.8.0b8)

![image](https://user-images.githubusercontent.com/2169849/55599556-64060280-5726-11e9-86d8-bb2a0421a59a.png)

## Logs

Not much I could find:

```
2019-03-30 16:02:34 [INFO ]: Starting module aw-server  (aw_qt.manager:46)
2019-03-30 16:02:34 [INFO ]: Starting module aw-watcher-afk  (aw_qt.manager:46)
2019-03-30 16:02:34 [INFO ]: Starting module aw-watcher-window  (aw_qt.manager:46)
2019-03-30 16:02:34 [INFO ]: Creating trayicon...  (aw_qt.trayicon:150)
2019-03-31 08:54:45 [WARNING]: Tried to stop module aw-watcher-window, but it wasn't running  (aw_qt.manager:84)
2019-03-31 09:03:11 [INFO ]: Starting module aw-watcher-window  (aw_qt.manager:46)
```

Might be related to https://github.com/ActivityWatch/activitywatch/issues/85 ?

**Comment by pcuci** [comment]
![image](https://user-images.githubusercontent.com/2169849/55601522-46896680-572f-11e9-975f-d8d617cc3d72.png)

3GiB worth of logs(!) in ~/AppData/Local/activitywatch/activitywatch/Logs/aw-server/aw-server_2019-03-17T11-09-47.log

```
...
Traceback (most recent call last):
  File "site-packages\flask\app.py", line 1813, in full_dispatch_request
  File "site-packages\flask\app.py", line 1799, in dispatch_request
  File "site-packages\flask_restplus\api.py", line 325, in wrapper
  File "site-packages\flask\views.py", line 88, in view
  File "site-packages\flask_restplus\resource.py", line 44, in dispatch_request
  File "aw_server\rest.py", line 226, in post
  File "aw_server\api.py", line 28, in g
  File "aw_server\api.py", line 209, in heartbeat
  File "site-packages\aw_datastore\datastore.py", line 132, in replace_last
  File "site-packages\aw_datastore\storages\peewee.py", line 158, in replace_last
  File "site-packages\aw_datastore\storages\peewee.py", line 154, in _get_last
  File "site-packages\peewee.py", line 6213, in get
aw_datastore.storages.peewee.EventModelDoesNotExist: <Model: EventModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."bucket_id", "t1"."timestamp", "t1"."duration", "t1"."datastr" FROM "eventmodel" AS "t1" WHERE ("t1"."bucket_id" = ?) ORDER BY "t1"."timestamp" DESC LIMIT ? OFFSET ?
Params: [2, 1, 0]
2019-03-21 20:38:53 [INFO ]: 500 (127.0.0.1): POST /api/0/buckets/aw-watcher-window_Paul-XPS/heartbeat?pulsetime=2.0 HTTP/1.1  (flask:25)
2019-03-21 20:38:53 [ERROR]: Exception on /api/0/buckets/aw-watcher-window_Paul-XPS/heartbeat [POST]  (flask.app:1761)
Traceback (most recent call last):
  File "site-packages\peewee.py", line 6208, in get
  File "site-packages\peewee.py", line 3883, in __getitem__
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\flask\app.py", line 1813, in full_dispatch_request
  File "site-packages\flask\app.py", line 1799, in dispatch_request
  File "site-packages\flask_restplus\api.py", line 325, in wrapper
  File "site-packages\flask\views.py", line 88, in view
  File "site-packages\flask_restplus\resource.py", line 44, in dispatch_request
  File "aw_server\rest.py", line 226, in post
  File "aw_server\api.py", line 28, in g
  File "aw_server\api.py", line 209, in heartbeat
  File "site-packages\aw_datastore\datastore.py", line 132, in replace_last
  File "site-packages\aw_datastore\storages\peewee.py", line 158, in replace_last
  File "site-packages\aw_datastore\storages\peewee.py", line 154, in _get_last
  File "site-packages\peewee.py", line 6213, in get
aw_datastore.storages.peewee.EventModelDoesNotExist: <Model: EventModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."bucket_id", "t1"."timestamp", "t1"."duration", "t1"."datastr" FROM "eventmodel" AS "t1" WHERE ("t1"."bucket_id" = ?) ORDER BY "t1"."timestamp" DESC LIMIT ? OFFSET ?
Params: [2, 1, 0]
2019-03-21 20:38:53 [INFO ]: 500 (127.0.0.1): POST /api/0/buckets/aw-watcher-window_Paul-XPS/heartbeat?pulsetime=2.0 HTTP/1.1  (flask:25)
```

**Comment by ErikBjare** [comment]
Huh, I have absolutely no clue what is going wrong here. Do you have any idea @johan-bjareholt?

**Comment by ErikBjare** [comment]
I'm not sure how to replicate this. Looks like the heartbeat can't find the most recent event when replacing the event, but it already got a `last_event` on line 209 in `api.py`, which is pretty weird.

Can you temporarily move the data folder and then try running again? If that doesn't help, try clearing the client queues.

If you don't know where to find those directories, we use: https://pypi.org/project/appdirs/ (we still haven't written the paths in the docs, sorry)

You didn't do something special that could have caused it? Just normal operation?
