### ISSUE TITLE
TypeError when creating a new bucket

### ISSUE THREAD

**Issue by jtrakk** [ActivityWatch/activitywatch#298]
I tried to create a new bucket but got an error.

```
ERROR in app: Exception on /api/0/buckets/screenshot-rgb [POST]
Traceback (most recent call last):
  File "site-packages/flask/app.py", line 1612, in full_dispatch_request
  File "site-packages/flask/app.py", line 1598, in dispatch_request
  File "site-packages/flask_restplus/api.py", line 313, in wrapper
  File "site-packages/flask/views.py", line 84, in view
  File "site-packages/flask_restplus/resource.py", line 44, in dispatch_request
  File "aw_server/rest.py", line 115, in post
TypeError: 'NoneType' object is not subscriptable
[INFO ]: 500 (127.0.0.1): POST /api/0/buckets/screenshot-rgb HTTP/1.1  (flask:25)

```

AW v0.7.1

**Comment by ErikBjare** [comment]
Please update ActivityWatch, there's really no reason to stay on v0.7.1

**Comment by jtrakk** [comment]
I was using that version because the others on GitHub said pre-release.

After upgrading to activitywatch-v0.8.0b9, I get the same error.

```

[ERROR]: Exception on /api/0/buckets/screenshot-rgb [POST]  (flask.app:1761)
Traceback (most recent call last):
  File "site-packages/flask/app.py", line 1813, in full_dispatch_request
  File "site-packages/flask/app.py", line 1799, in dispatch_request
  File "site-packages/flask_restplus/api.py", line 325, in wrapper
  File "site-packages/flask/views.py", line 88, in view
  File "site-packages/flask_restplus/resource.py", line 44, in dispatch_request
  File "aw_server/rest.py", line 122, in post
TypeError: 'NoneType' object is not subscriptable
INFO:flask:500 (127.0.0.1): POST /api/0/buckets/screenshot-rgb HTTP/1.1

```

**Comment by ErikBjare** [comment]
How are you creating the bucket? What's the payload?

**Comment by jtrakk** [comment]
```bash
$ curl -X POST "http://localhost:5600/api/0/buckets/screenshot-rgb"
```

Output:

```
{"message": "Internal Server Error"}
```

**Comment by johan-bjareholt** [comment]
@jtrakk Creating a new bucket requires a body with more data, just the name in the url is not sufficient. See http://127.0.0.1:5600/api/

This is the format of the body

```
{
  "client": "string",
  "type": "string",
  "hostname": "string"
}
```

**Comment by jtrakk** [comment]
Ok that works. Thanks.
