### ISSUE TITLE
Exception thrown while trying to get active window: <class 'Xlib.error.BadWindow'>

### ISSUE THREAD

**Issue by arthurlutz** [ActivityWatch/activitywatch#337]
## Describe the bug
Traceback / error in the logs. 

```
2020-01-27 11:10:59 [WARNING]: Unable to get window class, got a BadWindow exception.  (aw_watcher_window.xlib:85)

2020-01-27 11:10:59 [WARNING]: Code made an unclear branch  (aw_watcher_window.xlib:91)
2020-01-27 11:10:59 [WARNING]: Unable to get window query_tree().parent, got a BadWindow exception from Xlib  (aw_watcher_window.xlib:95)
2020-01-27 11:10:59 [WARNING]: Unable to get window property NET_WM_NAME, got a BadWindow exception from Xlib  (aw_watcher_window.xlib:54)
2020-01-27 11:10:59 [ERROR]: Exception thrown while trying to get active window: <class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x0880646f), sequence_number = 16751, major_opcode = 20, minor_opcode = 0  (aw_watcher_window.main:68)
Traceback (most recent call last):
  File "/home/arthur/.virtualenvs/activitywatch/lib/python3.6/site-packages/aw_watcher_window/main.py", line 65, in heartbeat_loop
    current_window = get_current_window()
  File "/home/arthur/.virtualenvs/activitywatch/lib/python3.6/site-packages/aw_watcher_window/lib.py", line 44, in get_current_window
    return get_current_window_linux()
  File "/home/arthur/.virtualenvs/activitywatch/lib/python3.6/site-packages/aw_watcher_window/lib.py", line 14, in get_current_window_linux
    name = xlib.get_window_name(window)
  File "/home/arthur/.virtualenvs/activitywatch/lib/python3.6/site-packages/aw_watcher_window/xlib.py", line 60, in get_window_name
    r = window.get_wm_name()
  File "/home/arthur/.virtualenvs/activitywatch/lib/python3.6/site-packages/Xlib/xobject/drawable.py", line 669, in get_wm_name
    return self.get_full_text_property(Xatom.WM_NAME, Xatom.STRING)
  File "/home/arthur/.virtualenvs/activitywatch/lib/python3.6/site-packages/Xlib/xobject/drawable.py", line 487, in get_full_text_property
    sizehint=sizehint)
  File "/home/arthur/.virtualenvs/activitywatch/lib/python3.6/site-packages/Xlib/xobject/drawable.py", line 472, in get_full_property
    prop = self.get_property(property, property_type, 0, sizehint)
  File "/home/arthur/.virtualenvs/activitywatch/lib/python3.6/site-packages/Xlib/xobject/drawable.py", line 461, in get_property
    long_length = length)
  File "/home/arthur/.virtualenvs/activitywatch/lib/python3.6/site-packages/Xlib/protocol/rq.py", line 1369, in __init__
    self.reply()
  File "/home/arthur/.virtualenvs/activitywatch/lib/python3.6/site-packages/Xlib/protocol/rq.py", line 1389, in reply
    raise self._error
Xlib.error.BadWindow: <class 'Xlib.error.BadWindow'>: code = 3, resource_id = <class 'Xlib.xobject.resource.Resource'>(0x0880646f), sequence_number = 16751, major_opcode = 20, minor_opcode = 0

```

## To Reproduce
Steps to reproduce the behavior: unknown, don't know what caused it. 

## Expected behavior
Since this doesn't impact activitywatch working correctly, maybe the error should be caught and not displayed as a traceback ? 

## Environment
 - ActivityWatch version: Version: v0.8.dev+c6433ea
 - OS: Linux (Ubuntu)

**Comment by nicolae-stroncea** [comment]
Could you try this while locking your screen(also maybe putting it to sleep)? I noticed that occasionally I will get unknown activity in the timeline and it seems to coincide with my laptop being locked/sleeping. I'm wondering if these 2 are related, where it gets the error and sets window title as unknown
