### ISSUE TITLE
Build .exe and .app with aw-server-rust and offer release that uses it

### ISSUE THREAD

**Issue by xylix** [ActivityWatch/activitywatch#353]
@ErikBjare @johan-bjareholt 

What are the blockers for this?

**Comment by ErikBjare** [comment]
For the `.exe` I think we're done,, we just haven't made a release since setting it up. Might need some testing though. 

For the `.app` you'll probably need to modify the `aw.spec` to include the aw-server-rust executable in the bundle somehow.

**Comment by xylix** [comment]
Do I need to set some config options or is there some artifact in the appveyor build that contains the .exe? I was looking into starting to use aw-server-rust on my windows box to test it out and afaik the newest build here https://ci.appveyor.com/project/ErikBjare/activitywatch runs aw-server by default.

I'll look into setting up the .app

**Comment by ErikBjare** [comment]
It'll run aw-server by default, but it should include aw-server-rust in the
build (it should appear in the aw-qt "modules" list). aw-qt can be
configured to autostart specific modules through CLI parameters.

**Comment by xylix** [comment]
Oh right. Makes sense. When I try to start my system installed aw-server-rust (installed by the name `aw-server`) on macOS, aw-qt silently crashes after trying to start it. 

The rust server runs fine if I start it from the CLI with `aw-server`.

(Log: 
```
2020-02-29 19:28:59 [INFO ]: Starting module aw-server  (aw_qt.manager:49)
2020-02-29 19:28:59 [INFO ]: Macos: Disable dock icon  (aw_qt.manager:67)
2020-02-29 19:28:59 [INFO ]: Starting module aw-watcher-afk  (aw_qt.manager:49)
2020-02-29 19:28:59 [INFO ]: Macos: Disable dock icon  (aw_qt.manager:67)
2020-02-29 19:28:59 [INFO ]: Starting module aw-watcher-window  (aw_qt.manager:49)
2020-02-29 19:28:59 [INFO ]: Macos: Disable dock icon  (aw_qt.manager:67)
2020-02-29 19:28:59 [INFO ]: Creating trayicon...  (aw_qt.trayicon:150)
2020-02-29 19:29:04 [INFO ]: Stopped module aw-server  (aw_qt.manager:97)
2020-02-29 19:29:06 [INFO ]: Starting module aw-server-rust  (aw_qt.manager:49)
2020-02-29 19:29:06 [INFO ]: Macos: Disable dock icon  (aw_qt.manager:67)
```)

Aw-server-rust doesn't write it's logs into the folder other activitywatch applications write it, ~/Library/Logs/activitywatch/<appname>. 

I could use any info about how aw-server-rust handles logging (especially on macOS if there's any specific setup). Pinging @johan-bjareholt

**Comment by xylix** [comment]
I found the log, it seems like the problem is in aw-qt's side.

```
Traceback (most recent call last):
  File "aw_qt/trayicon.py", line 117, in <lambda>
  File "aw_qt/manager.py", line 108, in toggle
  File "aw_qt/manager.py", line 73, in start
  File "subprocess.py", line 800, in __init__
  File "subprocess.py", line 1551, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'aw-server-rust': 'aw-server-rust'
```
So it's related to my installed aw-server-rust binary being named "aw-server" instead of aw-server-rust.

Should aw-qt even offer the aw-server-rust module option if it can't find it by that name on the system?

**Comment by johan-bjareholt** [comment]
I'm not sure how how we are supposed to do, @ErikBjare wanted a release where you could choose between aw-server and aw-server-rust if I understood him correctly. To me that doesn't make any sense because once you have migrated once you cannot migrate again unless you remove your database. The migration is one-way so it does not really make much sense to me to have a choice.

**Comment by ErikBjare** [comment]
Was this working on Windows and macOS?

**Comment by xylix** [comment]
@ErikBjare  Yes. All current features (as far as my normal usage and testing goes) work. 

A warning / info about the database migration being one-way could still be useful, but that's not in this issue's scope.
