### ISSUE TITLE
unable to build on win10

### ISSUE THREAD

**Issue by seujza** [ActivityWatch/activitywatch#497]
hi， I can not able to build the project. Please help in providing the necessary steps to solve the error.
Thanks a lot in advance.
```
(venv) D:\Code\activitywatch>make build
if [ -e "aw-core/.git" ]; then \
                echo "Submodules seem to already be initialized, continuing..."; \
        else \
                git submodule update --init --recursive; \
        fi
Submodules seem to already be initialized, continuing...
make --directory=aw-core build
make[1]: Entering directory `D:/Code/activitywatch/aw-core'
poetry install
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: aw-core (0.4.2)
make[1]: Leaving directory `D:/Code/activitywatch/aw-core'
make --directory=aw-client build
make[1]: Entering directory `D:/Code/activitywatch/aw-client'
poetry install
Installing dependencies from lock file

Package operations: 0 installs, 1 update, 0 removals

  • Updating aw-core (0.4.2 D:\Code\activitywatch\aw-core -> 0.4.2 2f8539b)

Installing the current project: aw-client (0.3.1)
make[1]: Leaving directory `D:/Code/activitywatch/aw-client'
make --directory=aw-watcher-afk build
make[1]: Entering directory `D:/Code/activitywatch/aw-watcher-afk'
poetry install
Installing dependencies from lock file

  PackageInfoError

  Unable to determine package info for path: C:\Users\J00356~1\AppData\Local\Temp\pypoetry-git-python-xlib7jbu65gt

  Fallback egg_info generation failed.

  Command C:\Users\J00356~1\AppData\Local\Temp\tmpzy6kq2c6\.venv\Scripts\python.exe setup.py egg_info errored with the following return code 1, and output:
  ERROR: Could not find a version that satisfies the requirement setuptools-scm (from versions: none)
  ERROR: No matching distribution found for setuptools-scm
  Traceback (most recent call last):
    File "C:\Users\J00356~1\AppData\Local\Temp\tmpzy6kq2c6\.venv\lib\site-packages\setuptools\installer.py", line 126, in fetch_build_egg
      subprocess.check_call(cmd)
    File "d:\software\python3.7\lib\subprocess.py", line 328, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['C:\\Users\\J00356~1\\AppData\\Local\\Temp\\tmpzy6kq2c6\\.venv\\Scripts\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\J00356~1\\AppData\\Local\\Temp\\tmpqf448kjy', '--quiet', 'setuptools-scm']' returned non-zero exit status 1.

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "setup.py", line 21, in <module>
      'Xlib.xobject'
    File "C:\Users\J00356~1\AppData\Local\Temp\tmpzy6kq2c6\.venv\lib\site-packages\setuptools\__init__.py", line 152, in setup
      _install_setup_requires(attrs)
    File "C:\Users\J00356~1\AppData\Local\Temp\tmpzy6kq2c6\.venv\lib\site-packages\setuptools\__init__.py", line 147, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "C:\Users\J00356~1\AppData\Local\Temp\tmpzy6kq2c6\.venv\lib\site-packages\setuptools\dist.py", line 676, in fetch_build_eggs
      replace_conflicting=True,
    File "C:\Users\J00356~1\AppData\Local\Temp\tmpzy6kq2c6\.venv\lib\site-packages\pkg_resources\__init__.py", line 766, in resolve
      replace_conflicting=replace_conflicting
    File "C:\Users\J00356~1\AppData\Local\Temp\tmpzy6kq2c6\.venv\lib\site-packages\pkg_resources\__init__.py", line 1049, in best_match
      return self.obtain(req, installer)
    File "C:\Users\J00356~1\AppData\Local\Temp\tmpzy6kq2c6\.venv\lib\site-packages\pkg_resources\__init__.py", line 1061, in obtain
      return installer(requirement)
    File "C:\Users\J00356~1\AppData\Local\Temp\tmpzy6kq2c6\.venv\lib\site-packages\setuptools\dist.py", line 732, in fetch_build_egg
      return fetch_build_egg(self, req)
    File "C:\Users\J00356~1\AppData\Local\Temp\tmpzy6kq2c6\.venv\lib\site-packages\setuptools\installer.py", line 128, in fetch_build_egg
      raise DistutilsError(str(e)) from e
  distutils.errors.DistutilsError: Command '['C:\\Users\\J00356~1\\AppData\\Local\\Temp\\tmpzy6kq2c6\\.venv\\Scripts\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\J00356~1\\AppData\\Local\\Temp\\tmpqf448kjy', '--quiet', 'setuptools-scm']' returned non-zero exit status 1.

  at d:\software\python3.7\lib\site-packages\poetry\inspection\info.py:498 in _pep517_metadata
      494│                     venv.run("python", "setup.py", "egg_info")
      495│                     return cls.from_metadata(path)
      496│                 except EnvCommandError as fbe:
      497│                     raise PackageInfoError(
    → 498│                         path, "Fallback egg_info generation failed.", fbe
      499│                     )
      500│                 finally:
      501│                     os.chdir(cwd.as_posix())
      502│
make[1]: *** [build] error 1
make[1]: Leaving directory `D:/Code/activitywatch/aw-watcher-afk'
make: *** [build] error 2
```

**Comment by ErikBjare** [comment]
We don't have the time to assist with build issues, especially on Windows. You're on your own, sorry.

**Comment by ErikBjare** [comment]
We don't have the time to assist with build issues, especially on Windows. You're on your own, sorry.
