### ISSUE TITLE
ActivityWatch crashes on Windows

### ISSUE THREAD

**Issue by MaskyS** [ActivityWatch/activitywatch#502]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS version and name**: Windows 10 18362
- **ActivityWatch version**: 0.9.2

## Describe the bug
ActivityWatch was working great initially, but now whenever I try opening it I get a dialog with "Module aw-watcher-window quit unexpectedly"; same msg for aw-watcher-afk and aw-server. Re-installing did not help. Trying to open dashboard/web api from tray icon doesn't work neither.

## Documentation
Logs are attached.
[Logs.zip](https://github.com/ActivityWatch/activitywatch/files/5443329/Logs.zip)

**Comment by ErikBjare** [comment]
Have you looked at #297 and confirmed you don't have a similar issue with corrupted config or data files?

The logs were unfortunately not helpful, as they seemed to be missing entirely for recent dates (possibly because the modules fail too early to have any time to emit logs). If you could provide output from running aw-server.exe directly from the command line that should give some useful hints as to what is going wrong.

**Comment by brimwats** [comment]
> Have you looked at #297 and confirmed you don't have a similar issue with corrupted config or data files?
> 
> The logs were unfortunately not helpful, as they seemed to be missing entirely for recent dates (possibly because the modules fail too early to have any time to emit logs). If you could provide output from running aw-server.exe (or any of the watchers) directly from the command line that should give some useful hints as to what is going wrong.

I have been having this same issue for days

```
C:\Program Files (x86)\ActivityWatch\aw-server>aw-server.exe
WARNING:root:Could not import pymongo, not available as a datastore backend
Traceback (most recent call last):
  File "__main__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\projects\activitywatch\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "aw_server\__init__.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\projects\activitywatch\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "aw_server\main.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\projects\activitywatch\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "aw_server\config.py", line 19, in <module>
  File "aw_core\config.py", line 23, in load_config
  File "configparser.py", line 718, in read_file
  File "configparser.py", line 1080, in _read
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'C:\\Users\\Brian\\AppData\\Local\\activitywatch\\activitywatch\\aw-server\\aw-server.ini', line: 1
'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
[16128] Failed to execute script __main__


```

**Comment by brimwats** [comment]
following this seems to fix it https://github.com/ActivityWatch/activitywatch/issues/297#issuecomment-520640138

but now i don't seem to have any data—can that be fixed?

**Comment by MaskyS** [comment]
> 
> 
> Have you looked at #297 and confirmed you don't have a similar issue with corrupted config or data files?
> 
> The logs were unfortunately not helpful, as they seemed to be missing entirely for recent dates (possibly because the modules fail too early to have any time to emit logs). If you could provide output from running aw-server.exe (or any of the watchers) directly from the command line that should give some useful hints as to what is going wrong.

Forgot to reply, but yes this fixed it for me.

**Comment by johan-bjareholt** [comment]
@brimwats If you only remove/rename the specific config file rather than moving the whole ActivityWatch folder all data should still be there.

According to the log message the file for you to rename/delete is located at "C:\\Users\\Brian\\AppData\\Local\\activitywatch\\activitywatch\\aw-server\\aw-server.ini"
