### ISSUE TITLE
Requests fails to build on Appveyor

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#52]
I was trying to implement a workaround for #51 when this happened: https://ci.appveyor.com/project/ErikBjare/activitywatch/build/job/nj0e99xty0vskdi2

<details>
<summary>Relevant output</summary>

```
Searching for requests
Reading https://pypi.python.org/simple/requests/
Downloading https://pypi.python.org/packages/4c/54/1d3abddbd4c7544138b88e8329ef5294ffdc6c5d7ea965bf42e3cc4c9c39/requests-2.16.1.tar.gz#md5=4acb351824461eb3ae1f74ec3a65ff28
Best match: requests 2.16.1
Processing requests-2.16.1.tar.gz
Writing C:\Users\appveyor\AppData\Local\Temp\1\easy_install-qoyp00fn\requests-2.16.1\setup.cfg
Running requests-2.16.1\setup.py -q bdist_egg --dist-dir C:\Users\appveyor\AppData\Local\Temp\1\easy_install-qoyp00fn\requests-2.16.1\egg-dist-tmp-rqjnti7r
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\setuptools\sandbox.py", line 157, in save_modules
    yield saved
  File "C:\Python35\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
    yield
  File "C:\Python35\lib\site-packages\setuptools\sandbox.py", line 255, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "C:\Python35\lib\site-packages\setuptools\sandbox.py", line 285, in run
    return func()
  File "C:\Python35\lib\site-packages\setuptools\sandbox.py", line 253, in runner
    _execfile(setup_script, ns)
  File "C:\Python35\lib\site-packages\setuptools\sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "C:\Users\appveyor\AppData\Local\Temp\1\easy_install-qoyp00fn\requests-2.16.1\setup.py", line 51, in <module>
  File "C:\Python35\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 441: character maps to <undefined>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "setup.py", line 18, in <module>
    'https://github.com/ActivityWatch/aw-core/tarball/master#egg=aw-core'
  File "C:\Python35\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Python35\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Python35\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python35\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Python35\lib\site-packages\setuptools\command\install.py", line 117, in do_egg_install
    cmd.run()
  File "C:\Python35\lib\site-packages\setuptools\command\easy_install.py", line 411, in run
    self.easy_install(spec, not self.no_deps)
  File "C:\Python35\lib\site-packages\setuptools\command\easy_install.py", line 654, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "C:\Python35\lib\site-packages\setuptools\command\easy_install.py", line 701, in install_item
    self.process_distribution(spec, dist, deps)
  File "C:\Python35\lib\site-packages\setuptools\command\easy_install.py", line 746, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "C:\Python35\lib\site-packages\pkg_resources\__init__.py", line 851, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "C:\Python35\lib\site-packages\pkg_resources\__init__.py", line 1123, in best_match
    return self.obtain(req, installer)
  File "C:\Python35\lib\site-packages\pkg_resources\__init__.py", line 1135, in obtain
    return installer(requirement)
  File "C:\Python35\lib\site-packages\setuptools\command\easy_install.py", line 673, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "C:\Python35\lib\site-packages\setuptools\command\easy_install.py", line 699, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "C:\Python35\lib\site-packages\setuptools\command\easy_install.py", line 880, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "C:\Python35\lib\site-packages\setuptools\command\easy_install.py", line 1119, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "C:\Python35\lib\site-packages\setuptools\command\easy_install.py", line 1105, in run_setup
    run_setup(setup_script, args)
  File "C:\Python35\lib\site-packages\setuptools\sandbox.py", line 258, in run_setup
    raise
  File "C:\Python35\lib\contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Python35\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
    yield
  File "C:\Python35\lib\contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Python35\lib\site-packages\setuptools\sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "C:\Python35\lib\site-packages\setuptools\sandbox.py", line 144, in resume
    six.reraise(type, exc, self._tb)
  File "C:\Python35\lib\site-packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Python35\lib\site-packages\setuptools\sandbox.py", line 157, in save_modules
    yield saved
  File "C:\Python35\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
    yield
  File "C:\Python35\lib\site-packages\setuptools\sandbox.py", line 255, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "C:\Python35\lib\site-packages\setuptools\sandbox.py", line 285, in run
    return func()
  File "C:\Python35\lib\site-packages\setuptools\sandbox.py", line 253, in runner
    _execfile(setup_script, ns)
  File "C:\Python35\lib\site-packages\setuptools\sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "C:\Users\appveyor\AppData\Local\Temp\1\easy_install-qoyp00fn\requests-2.16.1\setup.py", line 51, in <module>
  File "C:\Python35\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 441: character maps to <undefined>
```

</details>

**Comment by ErikBjare** [comment]
Fixed it with a workaround by downgrading requests to 2.14.1 for now (see the issue I filed in requests issues). Seems like it'll be fixed in an upcoming version.

**Comment by ErikBjare** [comment]
We could probably just remove the version constraint now as it's likely fixed in latest version of requests.

**Comment by ErikBjare** [comment]
Version constraint removed in 6e7c415. Now working as it should, closing.
