### ISSUE TITLE
Latest MacOS version fails to run version 0.11.0

### ISSUE THREAD

**Issue by kevich** [ActivityWatch/activitywatch#642]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: MacOS 11.4/11.5
- **ActivityWatch version**: 0.11.0

## Describe the bug
When you try to run ActivityWatch, it won't start at all.

## To Reproduce
Just try to run ActivityWatch 0.11.0 on MacOS 11.4/11.5

## Expected behavior
App will start normally

## Documentation
When you try to run in with `/Applications/ActivityWatch.app/Contents/MacOS/aw-qt` the log is following:
```
[19338] PyInstaller Bootloader 3.x
[19338] LOADER: executable is /Applications/ActivityWatch.app/Contents/MacOS/aw-qt
[19338] LOADER: homepath is /Applications/ActivityWatch.app/Contents/MacOS
[19338] LOADER: _MEIPASS2 is NULL
[19338] LOADER: archivename is /Applications/ActivityWatch.app/Contents/MacOS/aw-qt
[19338] LOADER: No need to extract files to run; setting extractionpath to homepath
[19338] LOADER: Already in the child - running user's code.
[19338] LOADER: Python library: /Applications/ActivityWatch.app/Contents/MacOS/libpython3.8.dylib
[19338] LOADER: Loaded functions from Python library.
[19338] LOADER: Manipulating environment (sys.path, sys.prefix)
[19338] LOADER: sys.prefix is /Applications/ActivityWatch.app/Contents/MacOS
[19338] LOADER: Pre-init sys.path is /Applications/ActivityWatch.app/Contents/MacOS/base_library.zip:/Applications/ActivityWatch.app/Contents/MacOS
[19338] LOADER: Setting runtime options
[19338] LOADER: Initializing python
[19338] LOADER: Overriding Python's sys.path
[19338] LOADER: Post-init sys.path is /Applications/ActivityWatch.app/Contents/MacOS/base_library.zip:/Applications/ActivityWatch.app/Contents/MacOS
[19338] LOADER: Setting sys.argv
[19338] LOADER: setting sys._MEIPASS
[19338] LOADER: importing modules from CArchive
[19338] LOADER: extracted struct
[19338] LOADER: callfunction returned...
[19338] LOADER: extracted pyimod01_os_path
[19338] LOADER: callfunction returned...
[19338] LOADER: extracted pyimod02_archive
[19338] LOADER: callfunction returned...
[19338] LOADER: extracted pyimod03_importers
[19338] LOADER: callfunction returned...
[19338] LOADER: Installing PYZ archive with Python modules.
[19338] LOADER: PYZ archive: PYZ-03.pyz
[19338] LOADER: Running pyiboot01_bootstrap.py
[19338] LOADER: Running pyi_rth__tkinter.py
[19338] LOADER: Running pyi_rth_multiprocessing.py
[19338] LOADER: Running pyi_rth_pyqt5.py
[19338] LOADER: Running pyi_rth_pkgres.py
[19338] LOADER: Running __main__.py
Traceback (most recent call last):
  File "aw_qt/__main__.py", line 3, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 760, in main
  File "click/_unicodefun.py", line 126, in _verify_python3_env
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/python3/ for mitigation steps.

This system lists a couple of UTF-8 supporting locales that you can pick from. The following suitable locales were discovered: af_ZA.UTF-8, am_ET.UTF-8, be_BY.UTF-8, bg_BG.UTF-8, ca_ES.UTF-8, cs_CZ.UTF-8, da_DK.UTF-8, de_AT.UTF-8, de_CH.UTF-8, de_DE.UTF-8, el_GR.UTF-8, en_AU.UTF-8, en_CA.UTF-8, en_GB.UTF-8, en_IE.UTF-8, en_NZ.UTF-8, en_US.UTF-8, es_ES.UTF-8, et_EE.UTF-8, eu_ES.UTF-8, fi_FI.UTF-8, fr_BE.UTF-8, fr_CA.UTF-8, fr_CH.UTF-8, fr_FR.UTF-8, he_IL.UTF-8, hr_HR.UTF-8, hu_HU.UTF-8, hy_AM.UTF-8, is_IS.UTF-8, it_CH.UTF-8, it_IT.UTF-8, ja_JP.UTF-8, kk_KZ.UTF-8, ko_KR.UTF-8, lt_LT.UTF-8, nl_BE.UTF-8, nl_NL.UTF-8, no_NO.UTF-8, pl_PL.UTF-8, pt_BR.UTF-8, pt_PT.UTF-8, ro_RO.UTF-8, ru_RU.UTF-8, sk_SK.UTF-8, sl_SI.UTF-8, sr_YU.UTF-8, sv_SE.UTF-8, tr_TR.UTF-8, uk_UA.UTF-8, zh_CN.UTF-8, zh_HK.UTF-8, zh_TW.UTF-8
[19338] Failed to execute script __main__
[19338] LOADER: OK.
[19338] LOADER: Cleaning up Python interpreter.
```

## Additional context
No Additional context

**Comment by chhantyal** [comment]
Upgraded to the latest version (both OSX & AW) and I also got this issue. See screenshot
<img width="382" alt="Screenshot 2021-09-29 at 17 40 24" src="https://user-images.githubusercontent.com/862941/135302743-8f24e88e-d1ef-452f-8e8d-cf416b4223ba.png">.

**Comment by Programmierus** [comment]
This is actually related to [issue](https://stackoverflow.com/questions/36651680/click-will-abort-further-execution-because-python-3-was-configured-to-use-ascii) of a wrong/missing locales for terminal applications.

You can still start already installed AW from the Terminal like this:

```sh
LC_ALL=en_US.utf-8 LANG=en_US.utf-8 open -a 'ActivityWatch'
```

**Comment by x-zheng16** [comment]
> Found solution - install from source
> 
> https://docs.activitywatch.net/en/latest/installing-from-source.html
> 
> Worked for me on MacOS Big Sur 11.6

Worked also for me on MacOS Monterey 12.3

**Comment by 23tux** [comment]
Is there any news on this?

**Comment by ErikBjare** [comment]
I hope nobody is experiencing this with v0.12.0 or v0.12.1.

Can we close this issue?

**Comment by ErikBjare** [comment]
Closing. Let me know if the issue still appears in recent versions.
