### ISSUE TITLE
ActivityWatch doesn't start in Archlinux

### ISSUE THREAD

**Issue by austinrojers** [ActivityWatch/activitywatch#660]
ActivityWatch doesn't start in Archlinux, I tried to install it from the AUR first and it didn't work.
Then I tried to install it by downloading it from the Github, it too gave me same errors:

```
 ╰─λ ./aw-qt
2021-09-01 15:20:08 [INFO ]: Searching for bundled modules in: ['/home/austin/.activitywatch/aw_qt', '/home/austin/.activitywatch']  (aw_qt.manager:67)
2021-09-01 15:20:08 [WARNING]: Found matching file but was not executable: /home/austin/.activitywatch/aw-server-rust/aw-server.service  (aw_qt.manager:54)
2021-09-01 15:20:08 [WARNING]: Found matching file but was not executable: /home/austin/.activitywatch/aw-qt.desktop  (aw_qt.manager:54)
2021-09-01 15:20:08 [INFO ]: Found bundled modules:  (aw_qt.manager:72)
2021-09-01 15:20:08 [INFO ]:  - aw-server at /home/austin/.activitywatch/aw-server/aw-server  (aw_qt.manager:24)
2021-09-01 15:20:08 [INFO ]:  - aw-watcher-window at /home/austin/.activitywatch/aw-watcher-window/aw-watcher-window  (aw_qt.manager:24)
2021-09-01 15:20:08 [INFO ]:  - aw-watcher-afk at /home/austin/.activitywatch/aw-watcher-afk/aw-watcher-afk  (aw_qt.manager:24)
2021-09-01 15:20:08 [INFO ]:  - aw-server-rust at /home/austin/.activitywatch/aw-server-rust/aw-server-rust  (aw_qt.manager:24)
2021-09-01 15:20:08 [INFO ]:  - aw-qt at /home/austin/.activitywatch/aw-qt  (aw_qt.manager:24)
2021-09-01 15:20:08 [INFO ]: Found system modules:  (aw_qt.manager:99)
2021-09-01 15:20:08 [INFO ]: Starting module aw-server  (aw_qt.manager:128)
2021-09-01 15:20:08 [INFO ]: Starting module aw-watcher-afk  (aw_qt.manager:128)
2021-09-01 15:20:08 [INFO ]: Starting module aw-watcher-window  (aw_qt.manager:128)
2021-09-01 15:20:08 [INFO ]: Creating trayicon...  (aw_qt.trayicon:206)
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

2021-09-01 15:20:08 [ERROR]: Another instance is already running, quitting.  (aw_client.singleinstance:40)
2021-09-01 15:20:09 [ERROR]: Another instance is already running, quitting.  (aw_client.singleinstance:40)
WARNING:root:Could not import pymongo, not available as a datastore backend
2021-09-01 15:20:09 [INFO ]: Using storage method: peewee  (aw_server.main:32)
2021-09-01 15:20:09 [INFO ]: Starting up...  (aw_server.main:37)
2021-09-01 15:20:09 [INFO ]: Using database file: /home/austin/.local/share/activitywatch/aw-server/peewee-sqlite.v2.db  (aw_datastore.storages.peewee:116)
 * Serving Flask app "aw-server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2021-09-01 15:20:09 [ERROR]: [Errno 98] Address already in use  (aw_server.server:112)
2021-09-01 15:20:09 [ERROR]: Unhandled exception  (root:43)
Traceback (most recent call last):
  File "__main__.py", line 3, in <module>
  File "aw_server/main.py", line 38, in main
  File "aw_server/server.py", line 113, in _start
  File "aw_server/server.py", line 103, in _start
  File "flask/app.py", line 990, in run
  File "werkzeug/serving.py", line 1052, in run_simple
  File "werkzeug/serving.py", line 996, in inner
  File "werkzeug/serving.py", line 862, in make_server
  File "werkzeug/serving.py", line 740, in __init__
  File "socketserver.py", line 452, in __init__
  File "http/server.py", line 138, in server_bind
  File "socketserver.py", line 466, in server_bind
OSError: [Errno 98] Address already in use
[69955] Failed to execute script __main__
fish: Job 1, './aw-qt' terminated by signal SIGABRT (Abort)
```

**Comment by ErikBjare** [comment]
Hmm, I think I've seen this issue before during testing, but I don't remember the cause...

I use Arch as well, and I can run the latest release on the AUR just fine. Not sure how our systems might differ?

**Comment by austinrojers** [comment]
Don't know, but maybe the devs can infer something from the logs

**Comment by ErikBjare** [comment]
I am the dev :sweat_smile:

Do the logs look the same when installed through the AUR? Which desktop environment are you using? Wayland or X11?

You could try running it with these env vars to see what the logs say: `QT_DEBUG=true QT_VERBOSE=true QT_DEBUG_PLUGINS=true`

**Comment by austinrojers** [comment]
Oh so sorry,😅
Yeah, the logs are almost the same, pointing to the issue when installed through the AUR,
I am running x11.
And where can I add those environment variables?
Thanks

**Comment by austinrojers** [comment]
I seems this is the issue: 

> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

(from the logs when installed by both the ways, AUR and github)

I would be great, if I could make it run.
It would be so useful for me.

Thank you

**Comment by ronanhansel** [comment]
I'm also facing the same error with the near identical log, I'm using Garuda Linux. It would be great to see this work again, it's such a nice app.

**Comment by austinrojers** [comment]
> I'm also facing the same error with the near identical log, I'm using Garuda Linux. It would be great to see this work again, it's such a nice app.


Technically speaking I too am using Garuda Linux not Arch

**Comment by rameltranquille** [comment]
I am on a vanilla arch and the same error occurs with the same output log

**Comment by austinrojers** [comment]
> Hmm, I think I've seen this issue before during testing, but I don't remember the cause...
> 
> I use Arch as well, and I can run the latest release on the AUR just fine. Not sure how our systems might differ?


Then how is it running fine for the developer?

**Comment by ErikBjare** [comment]
> And where can I add those environment variables?

@austinrojers You can run it with the env variables like this:

```
env QT_DEBUG=true QT_VERBOSE=true QT_DEBUG_PLUGINS=true ./aw-qt --testing --autostart-modules none
```

---

I have a feeling this has to do with an updated freetype2 (my system runs 2.10.4, upgrading to 2.11.0 now). Gonna investigate a bit.

**Comment by ronanhansel** [comment]
> ```
> env QT_DEBUG=true QT_VERBOSE=true QT_DEBUG_PLUGINS=true ./aw-qt --testing --autostart-modules none
> ```
Unfortunately, this doesn't seem to work either. And yes, I also think because of our up-to-date packages that is breaking the app since this problem occurs in all of my new installations Garuda, Manjaro, Arch (Basically it's all Arch). Good luck in fixing the error 👍🏻

**Comment by ErikBjare** [comment]
I've managed to reproduce (by updating) and build a release locally with the latest freetype 2.11.0 that runs fine.

Now the only issue is how to get that in CI, and figure out how it might affect older systems...

**Comment by ErikBjare** [comment]
After reading some discussion on the AUR and tracking down a similar issue for Steam, I found a fix: Remove the libharfbuzz.so.0 file from the installation directory.

This works fine on Arch for me, and I'll update the AUR package to include this workaround. 

For everyone else: will try to get it out of the next release entirely.

**Comment by austinrojers** [comment]
Thanks, @ErikBjare for fixing this issue. This is a great piece of software!
