### ISSUE TITLE
[Linux Mint 20.1] Port issue - Failed to reopen ActivityWatch

### ISSUE THREAD

**Issue by xjr007** [ActivityWatch/activitywatch#691]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **Linux Mint 20.1** 
- **0.11.0**

## Describe the bug
Upon opening and closing program via CLI, program fails to reopen on same port [5600]. Manually closing port resolves issue.

## To Reproduce
  Steps to reproduce the behaviour:
    1. Open CLI.
    2. Go to installation directory.
    3. Current directory is ./activitywatch.
    4. Run ./aw-qt from current directory.
    5. Wait for program to start.
    6. End program with Ctrl + C.
    7. Run ./aw-qt as before.

## Expected behaviour
Expected program to reopen exactly as it initially did the first time it was run.

## Documentation
2021-11-29 12:16:25 [INFO ]: Using storage method: peewee  (aw_server.main:32)
2021-11-29 12:16:25 [INFO ]: Starting up...  (aw_server.main:37)
2021-11-29 12:16:25 [INFO ]: Using database file: /home/[user]/.local/share/activitywatch/aw-server/peewee-sqlite.v2.db  (aw_datastore.storages.peewee:116)
2021-11-29 12:16:25 [ERROR]: [Errno 98] Address already in use  (aw_server.server:112)
2021-11-29 12:16:25 [ERROR]: Unhandled exception  (root:43)
Traceback (most recent call last):
  File "__main__.py", line 3, in <module>
  File "aw_server/main.py", line 38, in main
  File "aw_server/server.py", line 113, in _start
  File "aw_server/server.py", line 103, in _start
  File "flask/app.py", line 990, in run
  File "werkzeug/serving.py", line 1052, in run_simple
  File "werkzeug/serving.py", line 996, in inner
  File "werkzeug/serving.py", line 862, in make_server
  File "werkzeug/serving.py", line 740, in __init__
  File "socketserver.py", line 452, in __init__
  File "http/server.py", line 138, in server_bind
  File "socketserver.py", line 466, in server_bind
OSError: [Errno 98] Address already in use

**Comment by xjr007** [comment]
Thank you for responding.
