### ISSUE TITLE
aw-qt crashes if unreadable path in PATH

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/activitywatch#739]
The below was reported in another (resolved) issue, but it's unrelated.

---

I have the similar error.
1. Download: `aria 'https://github.com/ActivityWatch/activitywatch/releases/download/v0.12.0b1/activitywatch-v0.12.0b1-linux-x86_64.zip'
2. Unzip ` unzip activitywatch-v0.12.0b1-linux-x86_64.zip`
3. Run `./aw-qt`
```
2022-05-15 08:41:10 [INFO ]: Started aw-qt...  (aw_qt.main:31)
2022-05-15 08:41:10 [INFO ]: Searching for bundled modules in: ['/home/missu/activitywatch/aw_qt', '/home/missu/activitywatch']  (aw_qt.manager:71)
2022-05-15 08:41:10 [WARNING]: Found matching file but was not executable: /home/missu/activitywatch/aw-qt.desktop  (aw_qt.manager:55)
2022-05-15 08:41:10 [WARNING]: Found matching file but was not executable: /home/missu/activitywatch/aw-server-rust/aw-server.service  (aw_qt.manager:55)
2022-05-15 08:41:10 [INFO ]: Found bundled modules:  (aw_qt.manager:77)
2022-05-15 08:41:10 [INFO ]:  - aw-server-rust at /home/missu/activitywatch/aw-server-rust/aw-server-rust  (aw_qt.manager:24)
2022-05-15 08:41:10 [INFO ]:  - aw-watcher-afk at /home/missu/activitywatch/aw-watcher-afk/aw-watcher-afk  (aw_qt.manager:24)
2022-05-15 08:41:10 [INFO ]:  - aw-watcher-window at /home/missu/activitywatch/aw-watcher-window/aw-watcher-window  (aw_qt.manager:24)
2022-05-15 08:41:10 [INFO ]:  - aw-qt at /home/missu/activitywatch/aw-qt  (aw_qt.manager:24)
2022-05-15 08:41:10 [INFO ]:  - aw-server at /home/missu/activitywatch/aw-server/aw-server  (aw_qt.manager:24)
2022-05-15 08:41:10 [ERROR]: Unhandled exception  (root:53)
Traceback (most recent call last):
  File "aw_qt/__main__.py", line 3, in <module>
  File "click/core.py", line 1128, in __call__
  File "click/core.py", line 1053, in main
  File "click/core.py", line 1395, in invoke
  File "click/core.py", line 754, in invoke
  File "aw_qt/main.py", line 44, in main
  File "aw_qt/manager.py", line 223, in __init__
  File "aw_qt/manager.py", line 236, in discover_modules
  File "aw_qt/manager.py", line 94, in _discover_modules_system
PermissionError: [Errno 13] Permission denied: '/root'
[17531] Failed to execute script '__main__' due to unhandled exception!
```

System info: Arch Linux running RiverWM

_Originally posted by @mizzunet in https://github.com/ActivityWatch/activitywatch/issues/268#issuecomment-1126850398_

**Comment by ErikBjare** [comment]
My reply: https://github.com/ActivityWatch/activitywatch/issues/268#issuecomment-1126978587

So we need to just add a try/catch, a warning, and not let it crash just because some path in the PATH is misconfigured.
