### ISSUE TITLE
Exception thrown while trying to get active window

### ISSUE THREAD

**Issue by finnove** [ActivityWatch/activitywatch#742]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: macOS Monterey 
- **ActivityWatch version**: 0.12.0b2 

## Describe the bug
No data is gathered. I get a lot of exceptions in the log file. I have tried to add ActivityWatch to Accessibility in security, as requested in another thread. Does not help.
2022-05-30 11:46:32 [INFO ]: aw-watcher-window started  (aw_watcher_window.main:50)
2022-05-30 11:46:33 [INFO ]: Connection to aw-server established by aw-watcher-window  (aw_client.client:429)
2022-05-30 11:46:34 [ERROR]: Exception thrown while trying to get active window  (aw_watcher_window.main:75)
Traceback (most recent call last):
  File "aw_watcher_window/main.py", line 72, in heartbeat_loop
  File "aw_watcher_window/lib.py", line 55, in get_current_window
  File "aw_watcher_window/lib.py", line 27, in get_current_window_macos
  File "aw_watcher_window/macos_jxa.py", line 64, in getInfo
Exception: jxa error: Error: Error: An error occurred.
2022-05-30 11:46:35 [ERROR]: Exception thrown while trying to get active window  (aw_watcher_window.main:75)
Traceback (most recent call last):
  File "aw_watcher_window/main.py", line 72, in heartbeat_loop
  File "aw_watcher_window/lib.py", line 55, in get_current_window
  File "aw_watcher_window/lib.py", line 27, in get_current_window_macos
  File "aw_watcher_window/macos_jxa.py", line 64, in getInfo
Exception: jxa error: Error: Error: An error occurred.

## To Reproduce
Consistent. Will not work.

## Expected behavior
Installation should work without any special hacks or prior knowledge.

**Comment by msiwik-epruf** [comment]
Same bug on me.

**Comment by krlmlr** [comment]
Is this the same as https://github.com/ActivityWatch/aw-watcher-window/issues/60?

**Comment by BelKed** [comment]
I think this may help: https://github.com/ActivityWatch/activitywatch/issues/334#issuecomment-1052392579
(At least, in my case, it helped)

**Comment by finnove** [comment]
> There's a fix in the works, see here: [#334 (comment)](https://github.com/ActivityWatch/activitywatch/issues/334#issuecomment-1258166391)

Thank you. Data is coming in now, using v0.12.1.
