### ISSUE TITLE
DLL load failed while importing pythoncom: pyi_rth_win32comgenpy

### ISSUE THREAD

**Issue by BenjaminSymons** [ActivityWatch/activitywatch#804]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 10 Pro Version 10.0.19044 Build 19044
- **ActivityWatch version**: 0.12.1

## Describe the bug
aw-qt binary fails to properly launch the application; am immediately met with an unhandled exception in script. This happens when the program is installed and run or if launched from the extracted zip file. Potential exe build error?

## To Reproduce
    1. Install or download and unzip the latest release for windows
    2. Run aw-qt.exe
    3. See error

## Expected behavior
The application to launch

## Documentation
```
Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 52, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "win32com\__init__.py", line 6, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "pythoncom.py", line 4, in <module>
  File "pywintypes.py", line 118, in __import_pywin32_system_module__
ImportError: DLL load failed while importing pythoncom: The specified procedure could not be found.
```

## Additional context
Program never properly launches so there are no log files to attach

**Comment by SzilvasiPeter** [comment]
Hi, this problem occurs when multiple different pywintypes and pythoncom DLL exists. For example, if you have **pywin32** in anaconda and in python environment then the different versions will collide.

[Reinstall the pywin32](https://support.pyxll.com/hc/en-gb/articles/4404027796627--DLL-load-failed-The-specified-procedure-could-not-be-found-when-importing-win32api-or-win32com)
1. Uninstall pywin32 everywhere: `conda uninstall pywin32`, `pip uninstall pywinXX`
2. Remove DLLs everywhere: Search for "pythoncomXX.dll" and "pywintypesXX.dll" in the anaconda, python and C:\Windows\System32 locations. _Note: Replace XX with your python version._
3. [Install pywin32](https://pypi.org/project/pywin32/): Use `conda` OR `pip` for install
4. Register COM objects: `python Scripts/pywin32_postinstall.py -install`
