### ISSUE TITLE
Module aw-watcher-afk quits unexpectedly

### ISSUE THREAD

**Issue by sakshamb21** [ActivityWatch/activitywatch#805]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Solus 4.3
- **ActivityWatch version**: 0.12.1

## Describe the bug

Whenever i launch activitywatch, aw-qt returns with an error saying "Module aw-watcher-afk quit unexpectedly" and it doesent work at all

## To Reproduce

Run the aw-qt executable, and it returns with the error

## Documentation

The error details:
2022-10-04 13:14:10 [INFO ]: aw-watcher-afk started  (aw_watcher_afk.afk:60)
2022-10-04 13:14:11 [INFO ]: Connection to aw-server established by aw-watcher-afk  (aw_client.client:429)
2022-10-04 13:14:11 [ERROR]: Unhandled exception  (root:51)
Traceback (most recent call last):
  File "aw_watcher_afk/__main__.py", line 25, in <module>
  File "aw_watcher_afk/__main__.py", line 21, in main
  File "aw_watcher_afk/afk.py", line 70, in run
  File "aw_watcher_afk/afk.py", line 84, in heartbeat_loop
  File "aw_watcher_afk/unix.py", line 40, in seconds_since_last_input
  File "aw_watcher_afk/unix.py", line 13, in __init__
  File "aw_watcher_afk/listeners.py", line 78, in start
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "pynput/__init__.py", line 40, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "pynput/keyboard/__init__.py", line 31, in <module>
  File "pynput/_util/__init__.py", line 76, in backend
ImportError: this platform is not supported: ('failed to acquire X connection: Can\'t connect to display ":0": b\'Invalid MIT-MAGIC-COOKIE-1 key\'', DisplayConnectionError(':0', b'Invalid MIT-MAGIC-COOKIE-1 key'))

Try one of the following resolutions:

 * Please make sure that you have an X server running, and that the DISPLAY environment variable is set correctly

**Comment by sakshamb21** [comment]
It fixed by itself idk how
