### ISSUE TITLE
ActivityWatch triggers high WMI Provider Host CPU Usage

### ISSUE THREAD

**Issue by brimwats** [ActivityWatch/activitywatch#829]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: 
Edition	Windows 11 Education
Version	21H2
Installed on	‎11/‎24/‎2021
OS build	22000.1219
Experience	Windows Feature Experience Pack 1000.22000.1219.0

- **ActivityWatch version**: Host:  briaryVersion:  v0.12.1
- 

## Describe the bug
I have a debug log from aw-watcher-window that is 108mb that I cannot upload here. here is the Event Log from windows 11. The process ID is for window warcher. it triggers WMI provider Host to use up to 30% of the CPU and entirely chokes it at times. 
[aw.zip](https://github.com/ActivityWatch/activitywatch/files/10142215/aw.zip)

**Comment by dingwen07** [comment]
Same here, the WMI Provider Host constantly consuming significant amount of CPU as long as ActivityWatch is running.

No massibve error log for `aw-watcher-window` though, there is some like:

```
2023-01-08 05:31:57 [ERROR]: Exception thrown while trying to get active window  (aw_watcher_window.main:110)
Traceback (most recent call last):
  File "aw_watcher_window\main.py", line 107, in heartbeat_loop
  File "aw_watcher_window\lib.py", line 57, in get_current_window
  File "aw_watcher_window\lib.py", line 40, in get_current_window_windows
  File "aw_watcher_window\windows.py", line 26, in get_app_name
  File "wmi.py", line 1072, in query
  File "wmi.py", line 1072, in <listcomp>
  File "win32com\client\dynamic.py", line 324, in __getitem__
  File "win32com\client\util.py", line 41, in __getitem__
  File "win32com\client\util.py", line 62, in __GetIndex
pywintypes.com_error: (-2147217385, 'OLE error 0x80041017', None, None)
```

But I cannot reliability reproduce the error log.

**Comment by ErikBjare** [comment]
We have recently merged a PR that changes the method that window titles are retrieved on Windows, that should significantly improve performance.

**Comment by brimwats** [comment]
great news! thank you! should I leave the issue open until after the release?

**Comment by ErikBjare** [comment]
I'll close it, thanks for reporting :)
