### ISSUE TITLE
Timeline shows unknown window

### ISSUE THREAD

**Issue by AlexDumi29** [ActivityWatch/activitywatch#835]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Fedora 36 - Gnome+Wayland
- **ActivityWatch version**: tried the release v0.12.1 and v0.12.1.dev+ec18b64
## Describe the bug

The timeline just shows unknown.

## Expected behavior

Have the name and time I spent in each app

### aw-qt.log
```
2023-01-01 20:58:26 [INFO ]: Started aw-qt...  (aw_qt.main:53)
2023-01-01 20:58:26 [WARNING]: Found matching file but was not executable: /home/alex/activitywatch/aw-qt/aw-qt.spec  (aw_qt.manager:64)
2023-01-01 20:58:26 [INFO ]: Found 0 bundled modules  (aw_qt.manager:85)
2023-01-01 20:58:26 [INFO ]: Found 3 system modules  (aw_qt.manager:119)
2023-01-01 20:58:26 [INFO ]: Starting module aw-server  (aw_qt.manager:148)
2023-01-01 20:58:26 [INFO ]: Starting module aw-watcher-window  (aw_qt.manager:148)
2023-01-01 20:58:26 [INFO ]: Starting module aw-watcher-afk  (aw_qt.manager:148)
2023-01-01 20:58:26 [INFO ]: Creating trayicon...  (aw_qt.trayicon:206)
2023-01-01 20:58:26 [INFO ]: Initialized aw-qt and trayicon successfully  (aw_qt.trayicon:262)
2023-01-01 21:07:15 [INFO ]: Stopped module aw-server  (aw_qt.manager:195)
2023-01-01 21:07:15 [INFO ]: Stopped module aw-watcher-window  (aw_qt.manager:195)
2023-01-01 21:07:15 [INFO ]: Stopped module aw-watcher-afk  (aw_qt.manager:195)
```

### aw-server_2023-01-01T18-32-39.log
```
2023-01-01 18:32:39 [INFO ]: Using storage method: peewee  (aw_server.main:33)
2023-01-01 18:32:39 [INFO ]: Starting up...  (aw_server.main:41)
2023-01-01 18:32:39 [INFO ]: Using database file: /home/alex/.local/share/activitywatch/aw-server/peewee-sqlite.v2.db  (aw_datastore.storages.peewee:126)
2023-01-01 18:32:39 [INFO ]:  * Running on http://localhost:5600 (Press CTRL+C to quit)  (werkzeug:224)
2023-01-01 18:32:40 [INFO ]: Creating bucket 'aw-watcher-afk_legionalex'  (aw_datastore.datastore.Datastore:55)
2023-01-01 18:32:40 [INFO ]: Creating bucket 'aw-watcher-window_legionalex'  (aw_datastore.datastore.Datastore:55)
2023-01-01 18:32:51 [INFO ]: Received heartbeat, but bucket was previously empty, inserting as new event. (bucket: aw-watcher-window_legionalex)  (aw_server.api:291)
2023-01-01 18:34:18 [INFO ]: Creating bucket 'aw-stopwatch'  (aw_datastore.datastore.Datastore:55)
2023-01-01 18:35:41 [INFO ]: Received heartbeat, but bucket was previously empty, inserting as new event. (bucket: aw-watcher-afk_legionalex)  (aw_server.api:291)
2023-01-01 18:35:51 [INFO ]: Received heartbeat after pulse window, inserting as new event. (bucket: aw-watcher-afk_legionalex)  (aw_server.api:279)
```

### aw-server_2023-01-01T18-37-08.log
```
2023-01-01 18:37:08 [INFO ]: Using storage method: peewee  (aw_server.main:33)
2023-01-01 18:37:08 [INFO ]: Starting up...  (aw_server.main:41)
2023-01-01 18:37:08 [INFO ]: Using database file: /home/alex/.local/share/activitywatch/aw-server/peewee-sqlite.v2.db  (aw_datastore.storages.peewee:126)
2023-01-01 18:37:08 [INFO ]:  * Running on http://localhost:5600 (Press CTRL+C to quit)  (werkzeug:224)
2023-01-01 18:37:19 [INFO ]: Received heartbeat after pulse window, inserting as new event. (bucket: aw-watcher-window_legionalex)  (aw_server.api:279)
2023-01-01 18:40:19 [INFO ]: Received heartbeat after pulse window, inserting as new event. (bucket: aw-watcher-afk_legionalex)  (aw_server.api:279)
2023-01-01 20:13:25 [INFO ]: Received heartbeat after pulse window, inserting as new event. (bucket: aw-watcher-afk_legionalex)  (aw_server.api:279)
2023-01-01 20:13:32 [INFO ]: Received heartbeat after pulse window, inserting as new event. (bucket: aw-watcher-window_legionalex)  (aw_server.api:279)
2023-01-01 20:13:35 [INFO ]: Received heartbeat after pulse window, inserting as new event. (bucket: aw-watcher-afk_legionalex)  (aw_server.api:279)
```

### aw-server_2023-01-01T20-58-26.log
```
2023-01-01 20:58:26 [INFO ]: Using storage method: peewee  (aw_server.main:33)
2023-01-01 20:58:26 [INFO ]: Starting up...  (aw_server.main:41)
2023-01-01 20:58:26 [INFO ]: Using database file: /home/alex/.local/share/activitywatch/aw-server/peewee-sqlite.v2.db  (aw_datastore.storages.peewee:126)
2023-01-01 20:58:26 [INFO ]:  * Running on http://localhost:5600 (Press CTRL+C to quit)  (werkzeug:224)
2023-01-01 20:58:37 [INFO ]: Received heartbeat after pulse window, inserting as new event. (bucket: aw-watcher-window_legionalex)  (aw_server.api:279)
2023-01-01 21:01:38 [INFO ]: Received heartbeat after pulse window, inserting as new event. (bucket: aw-watcher-afk_legionalex)  (aw_server.api:279)
```

### aw-watcher-afk_2023-01-01T18-32-39.log
```
2023-01-01 18:32:39 [INFO ]: aw-watcher-afk started  (aw_watcher_afk.afk:60)
2023-01-01 18:32:40 [INFO ]: Connection to aw-server established by aw-watcher-afk  (aw_client.client:429)
2023-01-01 18:35:41 [INFO ]: Became AFK  (aw_watcher_afk.afk:97)
```

### aw-watcher-afk_2023-01-01T18-37-08.log
```
2023-01-01 18:37:08 [INFO ]: aw-watcher-afk started  (aw_watcher_afk.afk:60)
2023-01-01 18:37:09 [INFO ]: Connection to aw-server established by aw-watcher-afk  (aw_client.client:429)
2023-01-01 18:40:09 [INFO ]: Became AFK  (aw_watcher_afk.afk:97)
2023-01-01 18:42:34 [INFO ]: No longer AFK  (aw_watcher_afk.afk:90)
2023-01-01 20:13:25 [INFO ]: Became AFK  (aw_watcher_afk.afk:97)
```

### aw-watcher-afk_2023-01-01T20-58-26.log
```
2023-01-01 20:58:26 [INFO ]: aw-watcher-afk started  (aw_watcher_afk.afk:60)
2023-01-01 20:58:27 [INFO ]: Connection to aw-server established by aw-watcher-afk  (aw_client.client:436)
2023-01-01 21:01:27 [INFO ]: Became AFK  (aw_watcher_afk.afk:97)
2023-01-01 21:07:15 [INFO ]: aw-watcher-afk stopped by keyboard interrupt  (aw_watcher_afk.afk:116)
```

### aw-watcher-window_2023-01-01T18-32-39.log
```
2023-01-01 18:32:39 [INFO ]: aw-watcher-window started  (aw_watcher_window.main:62)
2023-01-01 18:32:40 [INFO ]: Connection to aw-server established by aw-watcher-window  (aw_client.client:429)
```

### aw-watcher-window_2023-01-01T18-37-08
```
2023-01-01 18:37:08 [INFO ]: aw-watcher-window started  (aw_watcher_window.main:62)
2023-01-01 18:37:09 [INFO ]: Connection to aw-server established by aw-watcher-window  (aw_client.client:429)
```

### aw-watcher-window_2023-01-01T20-58-26.log
```
2023-01-01 20:58:26 [INFO ]: aw-watcher-window started  (aw_watcher_window.main:62)
2023-01-01 20:58:27 [INFO ]: Connection to aw-server established by aw-watcher-window  (aw_client.client:436)
2023-01-01 21:07:15 [ERROR]: Unhandled exception  (root:52)
Traceback (most recent call last):
  File "/home/alex/activitywatch/venv/bin/aw-watcher-window", line 6, in <module>
    sys.exit(main())
  File "/home/alex/activitywatch/aw-watcher-window/aw_watcher_window/main.py", line 89, in main
    heartbeat_loop(
  File "/home/alex/activitywatch/aw-watcher-window/aw_watcher_window/main.py", line 144, in heartbeat_loop
    sleep(poll_time)
KeyboardInterrupt
```

## Additional context

 I saw a bug report that has since been reported fixed in v0.12.1 regarding this exact problem on macOS.

**Comment by AlexDumi29** [comment]
For the first two tries I've started the app using the instructions here: [Running on GNOME](https://docs.activitywatch.net/en/latest/running-on-gnome.html#running-on-gnome)

**Comment by AlexDumi29** [comment]
This seems to be a wayland issue as it works in the X11 session.

**Comment by AlexDumi29** [comment]
This is not an issue with Gnome as Plasma on Wayland has the same behavior.

**Comment by beh-10257** [comment]
I can confirm same problem in hyprland and sway

**Comment by Y4k3d0** [comment]
Bumping this to prevent it from closing.

Also happening with Arch + Hyprland.
