### ISSUE TITLE
[Beta][Windows]: aw-watcher-window crashes constantly with "Module use of python39.dll conflicts with this version of Python"

### ISSUE THREAD

**Issue by PetbkA** [ActivityWatch/activitywatch#936]
- [x] I am on the [latest **beta**](https://github.com/ActivityWatch/activitywatch/releases/tag/v0.12.3b7) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Windows 10 LTSC 2021 (version 21H2) x64 EN
- **ActivityWatch version**: 0.12.3b**7**

## Describe the bug
1. _aw-watcher-window_ worked OK with AW 0.12.3b**3** and Python 3.8.10 x64;
2. Then I installed 0.12.3b**7**, and watcher have started to restart cyclically with the folowing error in log:
```
2023-08-11 19:18:07 [ERROR]: Exception thrown while trying to get active window  (aw_watcher_window.main:124)
Traceback (most recent call last):
  File "aw_watcher_window\main.py", line 106, in heartbeat_loop
  File "aw_watcher_window\lib.py", line 65, in get_current_window
  File "aw_watcher_window\lib.py", line 39, in get_current_window_windows
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "aw_watcher_window\windows.py", line 6, in <module>
ImportError: Module use of python39.dll conflicts with this version of Python.
```
3. Tried to remove _Python 3.8.10 x64_ and install _3.11.4 x64_ with the same result;
4. Uninstalled _3.11.4_, but the same was with _Python 3.9.13 x64_.

## To Reproduce
1. Install Python 3.8.10 x64 with adding it to PATH - OK;
2. Install ActivityWatch 0.12.3b**7** on 0.12.3b**3** - OK;
3. Check _aw-watcher-window_'s logs for `conflicts with this version of Python` - NOK, constant errors are present, and watcher restarts continuosly.

## Expected behavior

1. There will be no `conflicts with this version of Python` in watcher's logs;
2. Watcher will be working.

**Comment by ErikBjare** [comment]
Thank you for reporting this!

I probably messed up something with the merge of https://github.com/ActivityWatch/activitywatch/pull/931.

I will investigate, thank you for a detailed report :)

**Comment by ErikBjare** [comment]
@BelKed This is the kind of "real-life testing" I was referring to in #931 :sweat_smile: 

Do you have any idea what could be the culprit here? I'm not sure where to begin.

**Comment by ErikBjare** [comment]
You can now try the new v0.12.3b8: https://github.com/ActivityWatch/activitywatch/releases/tag/v0.12.3b8

**Comment by PetbkA** [comment]
**0.12.3b6 x64 → 0.12.3b8 x64** - windows watcher doesn't crash but:
1. It still doesn't work;
2. `conflicts with this version of Python` error are still cyclical, although in other flabour:
    ```
2023-08-17 18:32:26 [INFO ]: aw-watcher-window started  (aw_watcher_window.main:62)
2023-08-17 18:32:27 [INFO ]: Connection to aw-server established by aw-watcher-window  (aw_client.client:436)
2023-08-17 18:32:28 [ERROR]: Exception thrown while trying to get active window  (aw_watcher_window.main:124)
Traceback (most recent call last):
  File "aw_watcher_window\main.py", line 106, in heartbeat_loop
  File "aw_watcher_window\lib.py", line 65, in get_current_window
  File "aw_watcher_window\lib.py", line 39, in get_current_window_windows
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "aw_watcher_window\windows.py", line 6, in <module>
ImportError: Module use of python39.dll conflicts with this version of Python.
```

**Comment by ErikBjare** [comment]
@PetbkA Thanks for validating!
