### ISSUE TITLE
AppImage does not launch on Ubuntu

### ISSUE THREAD

**Issue by mcmxcdev** [ActivityWatch/activitywatch#939]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Ubuntu 23.04
- **ActivityWatch version**: v0.12.3b8

## Describe the bug

The application crashes as soon as I execute it, logs can be seen below.

## Expected behavior
Expect application to launch normally

## Documentation

```
$ ./activitywatch-linux-x86_64_6aefaabc2876ceaee46b41d755e7f484.AppImage

QSocketNotifier: Can only be used with threads started with QThread
2023-08-19 16:30:00 [INFO ]: Started aw-qt...  (aw_qt.main:53)
2023-08-19 16:30:00 [WARNING]: Found matching file but was not executable: /tmp/.mount_activi9GUpIY/aw-qt.desktop  (aw_qt.manager:64)
2023-08-19 16:30:00 [INFO ]: Found 7 bundled modules  (aw_qt.manager:85)
2023-08-19 16:30:00 [INFO ]: Found 0 system modules  (aw_qt.manager:119)
2023-08-19 16:30:00 [INFO ]: Starting module aw-server  (aw_qt.manager:148)
2023-08-19 16:30:00 [INFO ]: Starting module aw-watcher-window  (aw_qt.manager:148)
2023-08-19 16:30:00 [INFO ]: Starting module aw-watcher-afk  (aw_qt.manager:148)
2023-08-19 16:30:00 [INFO ]: Creating trayicon...  (aw_qt.trayicon:206)
/tmp/.mount_activi9GUpIY/aw-qt: symbol lookup error: /tmp/.mount_activi9GUpIY/libQt6WaylandClient.so.6: undefined symbol: wl_proxy_marshal_flags
Traceback (most recent call last):
  File "PyInstaller/loader/pyimod02_importers.py", line 159, in get_code
Traceback (most recent call last):
  File "random.py", line 62, in <module>
  File "PyInstaller/loader/pyimod01_archive.py", line 180, in extract
ModuleNotFoundError: No module named '_sha512'

During handling of the above exception, another exception occurred:

OSError: [Errno 107] Transport endpoint is not connected: '/tmp/.mount_activi9GUpIY/aw-server/aw-server'
Traceback (most recent call last):

  File "PyInstaller/loader/pyimod02_importers.py", line 159, in get_code
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "PyInstaller/hooks/rthooks/pyi_rth_pkgres.py", line 200, in <module>
  File "PyInstaller/loader/pyimod01_archive.py", line 180, in extract
  File "PyInstaller/hooks/rthooks/pyi_rth_pkgres.py", line 36, in _pyi_rthook
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/.mount_activi9GUpIY/aw-watcher-afk/aw-watcher-afk'
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "PyInstaller/hooks/rthooks/pyi_rth_pkgres.py", line 200, in <module>                                                                                                              
  File "pkg_resources/__init__.py", line 36, in <module>
  File "PyInstaller/hooks/rthooks/pyi_rth_pkgres.py", line 36, in _pyi_rthook
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "email/parser.py", line 12, in <module>
  File "pkg_resources/__init__.py", line 36, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "email/feedparser.py", line 27, in <module>
  File "email/parser.py", line 12, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "email/_policybase.py", line 9, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "email/feedparser.py", line 27, in <module>
  File "email/utils.py", line 29, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "PyInstaller/loader/pyimod02_importers.py", line 366, in exec_module
  File "email/_policybase.py", line 9, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 161, in get_code
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
ImportError: PyiFrozenImporter cannot handle module 'socket'
  File "email/utils.py", line 28, in <module>
[101012] Failed to execute script 'pyi_rth_pkgres' due to unhandled exception!
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "random.py", line 65, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 366, in exec_module
  File "PyInstaller/loader/pyimod02_importers.py", line 161, in get_code
ImportError: PyiFrozenImporter cannot handle module 'hashlib'
[101014] Failed to execute script 'pyi_rth_pkgres' due to unhandled exception!
```

**Comment by nonno-cicala** [comment]
The AppImage of version 0.12.2 works for me, while versions 0.13.0 and 0.13.1 throw that error:
```
/tmp/.mount_activiph3nd8/aw-qt: symbol lookup error: /tmp/.mount_activiph3nd8/libQt6WaylandClient.so.6: undefined symbol: wl_proxy_marshal_flags
```

I have the same problem with the deb package of version 0.13.1 (I didn't try the deb 0.13.0)
