### ISSUE TITLE
Category Builder keep showing "loading" 

### ISSUE THREAD

**Issue by JaydonZhao** [ActivityWatch/activitywatch#965]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **windows11 22H2**: 
- **Version:  v0.12.3b10**: 

## To Reproduce

  Steps to reproduce the behavior, for example:
    1. Go to 'Category Builder'
    2. The page keeping showing "loading

### Screenshot
![image](https://github.com/ActivityWatch/activitywatch/assets/43411963/8ae0672c-861e-4425-b7ae-e3a491ce1277)

#### Log of aw-watcher-window: 
2023-10-12 02:19:00 [ERROR]: Exception thrown while trying to get active window  (aw_watcher_window.main:124)
Traceback (most recent call last):
  File "aw_watcher_window\main.py", line 106, in heartbeat_loop
  File "aw_watcher_window\lib.py", line 65, in get_current_window
  File "aw_watcher_window\lib.py", line 42, in get_current_window_windows
  File "aw_watcher_window\windows.py", line 26, in get_app_name
  File "aw_watcher_window\windows.py", line 15, in get_app_path
pywintypes.error: (5, 'OpenProcess', 'Access is denied.')

#### Lof of aw-server
2023-10-12 02:25:29 [WARNING]: Gap was of negative duration but could be safely merged (-306.503s). This message will only show once per batch.  (aw_transform.flood:46)
2023-10-12 02:25:29 [WARNING]: Gap was of negative duration but could be safely merged (-2622.032s). This message will only show once per batch.  (aw_transform.flood:46)
2023-10-12 02:25:29 [WARNING]: Gap was of negative duration but could be safely merged (-313.812s). This message will only show once per batch.  (aw_transform.flood:46)
2023-10-12 02:25:29 [WARNING]: Gap was of negative duration but could be safely merged (-711.984s). This message will only show once per batch.  (aw_transform.flood:46)
2023-10-12 02:25:29 [WARNING]: Gap was of negative duration but could be safely merged (-2099.711s). This message will only show once per batch.  (aw_transform.flood:46)
2023-10-12 02:25:29 [WARNING]: Gap was of negative duration but could be safely merged (-113.681s). This message will only show once per batch.  (aw_transform.flood:46)
2023-10-12 02:25:31 [INFO ]: 400 (127.0.0.1): [31m[1mPOST /api/0/query/ HTTP/1.1[0m  (flask:25)
2023-10-12 02:31:32 [WARNING]: Gap was of negative duration but could be safely merged (-286.389s). This message will only show once per batch.  (aw_transform.flood:46)
2023-10-12 02:31:34 [WARNING]: Gap was of negative duration but could be safely merged (-286.389s). This message will only show once per batch.  (aw_transform.flood:46)
2023-10-12 02:31:42 [INFO ]: 400 (127.0.0.1): [31m[1mPOST /api/0/query/ HTTP/1.1[0m  (flask:25)

**Comment by JaydonZhao** [comment]
Find another issue that is similar #905

**Comment by Qemuel8** [comment]
this coment is a repost of the comment i wrote on issue #905 

So the way i fixed this could also solve it for other.
-Go to category builder.
-Press Show Options.
-Select a different host name.

as i understand my issue was related to having an old watcher that i wasnt using and was deleted but was still showing in the list of hosts. Picking the new host solved the problem for me.

**Comment by JaydonZhao** [comment]
@Qemuel8 It works for me! Thanks❤!! 
Don't know why the default hostname is "unknow", but after I change it to my computer, it works!!

**Comment by ErikBjare** [comment]
In https://github.com/ActivityWatch/aw-webui/commit/fcbd586521c8865953745c9257fa6da6819b2217 I fixed it such that the default host is the one with the most recent data.

And in https://github.com/ActivityWatch/aw-webui/commit/819c4e3e16ce2984ae2546f97f657d7c225e7cf7 I fixed it such that it will never choose "unknown" (will always fail).
