### ISSUE TITLE
Internal Server Error, with the default Categorization, no extra regex

### ISSUE THREAD

**Issue by borislavib** [ActivityWatch/activitywatch#967]
Hi team, 

I'm having "Internal Server Error" and I already removed all regexes(as the similar bugfix suggests). Now I'm with the default regex but still have this issue.

 - [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

 

- **OS name and version**: Windows 10
- **ActivityWatch version**: Version:  v0.12.2

## Describe the bug
Just open the app

## To Reproduce
Internal Server Error
--> everything is loading 

## Expected behavior
No internal server

## Additional context
**aw-server log** : 

 2023-10-13   [ERROR]: Exception on /api/0/query/ [POST]  (aw-server:1449)
Traceback (most recent call last):
  File "flask\app.py", line 1517, in full_dispatch_request
  File "flask\app.py", line 1503, in dispatch_request
  File "aw_server\rest.py", line 46, in decorator
  File "flask_restx\api.py", line 405, in wrapper
  File "flask\views.py", line 84, in view
  File "flask_restx\resource.py", line 46, in dispatch_request
  File "aw_server\rest.py", line 323, in post
  File "aw_server\api.py", line 310, in query2
  File "aw_query\query2.py", line 417, in query
  File "aw_query\query2.py", line 391, in interpret
  File "aw_query\query2.py", line 140, in interpret
  File "aw_query\functions.py", line 88, in g
  File "aw_query\functions.py", line 117, in g
  File "aw_query\functions.py", line 198, in q2_filter_keyvals_regex
  File "aw_transform\filter_keyvals.py", line 28, in filter_keyvals_regex
  File "aw_transform\filter_keyvals.py", line 28, in <listcomp>
  File "aw_transform\filter_keyvals.py", line 26, in predicate
KeyError: 'title'

**aw-watcher-window log**
2023-10-13  [ERROR]: Exception thrown while trying to get active window  (aw_watcher_window.main:124)
Traceback (most recent call last):
  File "aw_watcher_window\main.py", line 106, in heartbeat_loop
  File "aw_watcher_window\lib.py", line 65, in get_current_window
  File "aw_watcher_window\lib.py", line 42, in get_current_window_windows
  File "aw_watcher_window\windows.py", line 26, in get_app_name
  File "aw_watcher_window\windows.py", line 15, in get_app_path
pywintypes.error: (87, 'OpenProcess', 'The parameter is incorrect.')

**Comment by BelKed** [comment]
I've fixed the problem in https://github.com/ActivityWatch/aw-core/pull/123 some time ago.
Could you please try to upgrade to the [latest beta version](https://github.com/ActivityWatch/activitywatch/releases/tag/v0.12.3b10)?
If the problem persists, please let us know :)

**Comment by borislavib** [comment]
@BelKed It looks like the problem was only last week, on Friday. This week it's working.
